; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
rpm		EQU	01234H		; @ram @0x1234 (uint16_t)

	.section .text
	.global read_rpm

read_rpm:
	PUSH     R15                 ; save caller's frame pointer
	MOV      R15, SP             ; establish frame pointer
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/abs_ram_global.c:6
	MOV      R0, rpm             ; R0 = rpm
	POP      R15                 ; restore caller's frame pointer
	RET                          
