; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global add

add:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'a'
	MOV      [R15+#2], R5        ; spill incoming parameter 'b'
	; source: examples/add.c:3
	MOV      R0, [R15+#0]        ; R0 = a
	MOV      R1, [R15+#2]        ; R1 = b
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, R2              ; return value
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

