; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global bubble_sort

bubble_sort:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #10             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'v'
	MOV      [R15+#2], R5        ; spill incoming parameter 'n'
	; source: examples/bubble_sort.c:4
	MOV      R0, #0              
	MOV      [R15+#4], R0        ; i = R0
.Lbubble_sort_for_cond_0:
	MOV      R0, [R15+#4]        ; R0 = i
	MOV      R1, [R15+#2]        ; R1 = n
	CMP      R0, R1              
	JMPR     cc_C, .Lbubble_sort_cmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lbubble_sort_cmp_end_1
.Lbubble_sort_cmp_true_1:
	MOV      R2, #1              
.Lbubble_sort_cmp_end_1:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lbubble_sort_for_body_1
	JMPR     cc_UC, .Lbubble_sort_for_end_3
.Lbubble_sort_for_body_1:
	; source: examples/bubble_sort.c:5
	MOV      R0, #0              
	MOV      [R15+#6], R0        ; j = R0
.Lbubble_sort_for_cond_4:
	MOV      R0, [R15+#6]        ; R0 = j
	MOV      R1, [R15+#2]        ; R1 = n
	MOV      R2, [R15+#4]        ; R2 = i
	MOV      R3, R1              
	SUB      R3, R2              
	MOV      R1, #1              
	MOV      R2, R3              
	SUB      R2, R1              
	CMP      R0, R2              
	JMPR     cc_C, .Lbubble_sort_cmp_true_2
	MOV      R1, #0              
	JMPR     cc_UC, .Lbubble_sort_cmp_end_2
.Lbubble_sort_cmp_true_2:
	MOV      R1, #1              
.Lbubble_sort_cmp_end_2:
	CMP      R1, #0              
	JMPR     cc_NZ, .Lbubble_sort_for_body_5
	JMPR     cc_UC, .Lbubble_sort_for_end_7
.Lbubble_sort_for_body_5:
	; source: examples/bubble_sort.c:6
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, [R15+#6]        ; R1 = j
	MOV      R2, #2              
	MULU     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      R0, [R1]            
	MOV      R1, [R15+#0]        ; R1 = v
	MOV      R2, [R15+#6]        ; R2 = j
	MOV      R3, #1              
	MOV      R8, R2              
	ADD      R8, R3              
	MOV      R2, #2              
	MULU     R8, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R2, R1              
	ADD      R2, R3              
	MOV      R1, [R2]            
	CMP      R0, R1              
	JMPR     cc_UGT, .Lbubble_sort_cmp_true_3
	MOV      R2, #0              
	JMPR     cc_UC, .Lbubble_sort_cmp_end_3
.Lbubble_sort_cmp_true_3:
	MOV      R2, #1              
.Lbubble_sort_cmp_end_3:
	; source: examples/bubble_sort.c:11
	CMP      R2, #0              
	JMPR     cc_NZ, .Lbubble_sort_if_then_8
	JMPR     cc_UC, .Lbubble_sort_if_end_10
.Lbubble_sort_if_then_8:
	; source: examples/bubble_sort.c:7
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, [R15+#6]        ; R1 = j
	MOV      R2, #2              
	MULU     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      R0, [R1]            
	MOV      [R15+#8], R0        ; tmp = R0
	; source: examples/bubble_sort.c:8
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, [R15+#6]        ; R1 = j
	MOV      R2, #1              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, #2              
	MULU     R3, R1              
	MOV      R2, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R2              
	MOV      R0, [R1]            
	MOV      R1, [R15+#0]        ; R1 = v
	MOV      R2, [R15+#6]        ; R2 = j
	MOV      R3, #2              
	MULU     R2, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R2, R1              
	ADD      R2, R8              
	MOV      [R2], R0            
	; source: examples/bubble_sort.c:9
	MOV      R0, [R15+#8]        ; R0 = tmp
	MOV      R1, [R15+#0]        ; R1 = v
	MOV      R2, [R15+#6]        ; R2 = j
	MOV      R3, #1              
	MOV      R8, R2              
	ADD      R8, R3              
	MOV      R2, #2              
	MULU     R8, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R2, R1              
	ADD      R2, R3              
	MOV      [R2], R0            
.Lbubble_sort_if_end_10:
.Lbubble_sort_for_post_6:
	; source: examples/bubble_sort.c:5
	MOV      R0, [R15+#6]        ; R0 = j
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#6], R2        ; j = R2
	JMPR     cc_UC, .Lbubble_sort_for_cond_4
.Lbubble_sort_for_end_7:
.Lbubble_sort_for_post_2:
	; source: examples/bubble_sort.c:4
	MOV      R0, [R15+#4]        ; R0 = i
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#4], R2        ; i = R2
	JMPR     cc_UC, .Lbubble_sort_for_cond_0
.Lbubble_sort_for_end_3:
	ADD      SP, #10             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

