; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global calculate

calculate:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'rpm'
	MOV      [R15+#2], R5        ; spill incoming parameter 'load'
	; source: examples/calculate.c:3
	MOV      R0, [R15+#0]        ; R0 = rpm
	MOV      R1, #3000           
	CMP      R0, R1              
	JMPR     cc_UGT, .Lcmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lcmp_end_1  
.Lcmp_true_1:
	MOV      R2, #1              
.Lcmp_end_1:
	; source: examples/calculate.c:6
	CMP      R2, #0              
	JMPR     cc_NZ, .Lcalculate_if_then_0
	JMPR     cc_UC, .Lcalculate_if_end_2
.Lcalculate_if_then_0:
	; source: examples/calculate.c:4
	MOV      R0, [R15+#2]        ; R0 = load
	MOV      R1, #10             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, R2              ; return value
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Lcalculate_if_end_2:
	; source: examples/calculate.c:6
	MOV      R0, [R15+#2]        ; R0 = load
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

