; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
IN_X:		DS	2		; uint16_t
IN_V:		DS	2		; uint16_t
OUT:		DS	2		; uint16_t

	.section .text
	.global f
	.global call_liveness

f:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'x'
	MOV      [R15+#2], R5        ; spill incoming parameter 'v'
	; source: examples/call_liveness.c:18
	MOV      R0, [R15+#0]        ; R0 = x
	MOV      R1, [R15+#2]        ; R1 = v
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, #4660           
	MOV      R1, R2              
	XOR      R1, R0              
	MOV      R0, R1              ; return value
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

call_liveness:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/call_liveness.c:24
	MOV      R0, IN_V            ; R0 = IN_V
	MOV      [R15+#0], R0        ; v = R0
	; source: examples/call_liveness.c:25
	MOV      R11, [R15+#0]       ; R11 = v
	MOV      [R15+#2], R11       
	MOV      R0, IN_X            ; R0 = IN_X
	MOV      R1, [R15+#0]        ; R1 = v
	MOV      R4, R0              
	MOV      R5, R1              
	CALLR    f                   
	MOV      R2, R0              ; function result
	MOV      R11, [R15+#2]       ; reload spilled value
	MOV      R0, R11             
	ADD      R0, R2              
	MOV      [R15+#0], R0        ; v = R0
	; source: examples/call_liveness.c:26
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      OUT, R0             ; OUT = R0
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

