; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
OUT:		DS	2		; uint16_t

	.section .text
	.global cast_qualifier_fixed_addr

cast_qualifier_fixed_addr:
	PUSH     R15                 ; save caller's frame pointer
	MOV      R15, SP             ; establish frame pointer
	; source: examples/cast_qualifier_fixed_addr.c:11
	MOV      R0, #42             
	MOV      R1, #64912          
	MOV      [R1], R0            
	; source: examples/cast_qualifier_fixed_addr.c:12
	MOV      R0, #64912          
	MOV      R1, [R0]            
	MOV      OUT, R1             ; OUT = R1
	POP      R15                 ; restore caller's frame pointer
	RET                          

