; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global bug14
	.global sem_chaves
	.global break_continue
	.global aninhado

bug14:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'n'
	; source: examples/do_while.c:8
	MOV      R0, #0              
	MOV      [R15+#2], R0        ; i = R0
.Lbug14_do_body_0:
	; source: examples/do_while.c:10
	MOV      R0, [R15+#2]        ; R0 = i
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#2], R2        ; i = R2
	; source: examples/do_while.c:11
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #1              
	MOV      R2, R0              
	SHR      R2, R1              
	MOV      [R15+#0], R2        ; n = R2
.Lbug14_do_cond_1:
	; source: examples/do_while.c:12
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #0              
	CMP      R0, R1              
	JMPR     cc_NZ, .Lbug14_cmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lbug14_cmp_end_1
.Lbug14_cmp_true_1:
	MOV      R2, #1              
.Lbug14_cmp_end_1:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lbug14_do_body_0
.Lbug14_do_end_2:
	; source: examples/do_while.c:13
	MOV      R0, [R15+#2]        ; R0 = i
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

sem_chaves:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'n'
.Lsem_chaves_do_body_0:
	; source: examples/do_while.c:19
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #1              
	MOV      R2, R0              
	SUB      R2, R1              
	MOV      [R15+#0], R2        ; n = R2
.Lsem_chaves_do_cond_1:
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #10             
	CMP      R0, R1              
	JMPR     cc_UGT, .Lsem_chaves_cmp_true_2
	MOV      R2, #0              
	JMPR     cc_UC, .Lsem_chaves_cmp_end_2
.Lsem_chaves_cmp_true_2:
	MOV      R2, #1              
.Lsem_chaves_cmp_end_2:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lsem_chaves_do_body_0
.Lsem_chaves_do_end_2:
	; source: examples/do_while.c:20
	MOV      R0, [R15+#0]        ; R0 = n
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

break_continue:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'lim'
	; source: examples/do_while.c:26
	MOV      R0, #0              
	MOV      [R15+#2], R0        ; k = R0
	; source: examples/do_while.c:27
	MOV      R0, #0              
	MOV      [R15+#4], R0        ; sum = R0
.Lbreak_continue_do_body_0:
	; source: examples/do_while.c:29
	MOV      R0, [R15+#2]        ; R0 = k
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#2], R2        ; k = R2
	; source: examples/do_while.c:30
	MOV      R0, [R15+#2]        ; R0 = k
	MOV      R1, #9              
	CMP      R0, R1              
	JMPR     cc_UGT, .Lbreak_continue_cmp_true_3
	MOV      R2, #0              
	JMPR     cc_UC, .Lbreak_continue_cmp_end_3
.Lbreak_continue_cmp_true_3:
	MOV      R2, #1              
.Lbreak_continue_cmp_end_3:
	; source: examples/do_while.c:31
	CMP      R2, #0              
	JMPR     cc_NZ, .Lbreak_continue_if_then_3
	JMPR     cc_UC, .Lbreak_continue_if_end_5
.Lbreak_continue_if_then_3:
	JMPR     cc_UC, .Lbreak_continue_do_end_2
.Lbreak_continue_if_end_5:
	MOV      R0, [R15+#2]        ; R0 = k
	MOV      R1, #1              
	MOV      R2, R0              
	AND      R2, R1              
	MOV      R0, #0              
	CMP      R2, R0              
	JMPR     cc_Z, .Lbreak_continue_cmp_true_4
	MOV      R1, #0              
	JMPR     cc_UC, .Lbreak_continue_cmp_end_4
.Lbreak_continue_cmp_true_4:
	MOV      R1, #1              
.Lbreak_continue_cmp_end_4:
	; source: examples/do_while.c:32
	CMP      R1, #0              
	JMPR     cc_NZ, .Lbreak_continue_if_then_6
	JMPR     cc_UC, .Lbreak_continue_if_end_8
.Lbreak_continue_if_then_6:
	JMPR     cc_UC, .Lbreak_continue_do_cond_1
.Lbreak_continue_if_end_8:
	MOV      R0, [R15+#4]        ; R0 = sum
	MOV      R1, [R15+#2]        ; R1 = k
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#4], R2        ; sum = R2
.Lbreak_continue_do_cond_1:
	; source: examples/do_while.c:33
	MOV      R0, [R15+#2]        ; R0 = k
	MOV      R1, [R15+#0]        ; R1 = lim
	CMP      R0, R1              
	JMPR     cc_C, .Lbreak_continue_cmp_true_5
	MOV      R2, #0              
	JMPR     cc_UC, .Lbreak_continue_cmp_end_5
.Lbreak_continue_cmp_true_5:
	MOV      R2, #1              
.Lbreak_continue_cmp_end_5:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lbreak_continue_do_body_0
.Lbreak_continue_do_end_2:
	; source: examples/do_while.c:34
	MOV      R0, [R15+#4]        ; R0 = sum
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

aninhado:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #8              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'n'
	; source: examples/do_while.c:41
	MOV      R0, #0              
	MOV      [R15+#2], R0        ; total = R0
.Laninhado_while_cond_0:
	; source: examples/do_while.c:42
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #0              
	CMP      R0, R1              
	JMPR     cc_UGT, .Laninhado_cmp_true_6
	MOV      R2, #0              
	JMPR     cc_UC, .Laninhado_cmp_end_6
.Laninhado_cmp_true_6:
	MOV      R2, #1              
.Laninhado_cmp_end_6:
	CMP      R2, #0              
	JMPR     cc_NZ, .Laninhado_while_body_1
	JMPR     cc_UC, .Laninhado_while_end_2
.Laninhado_while_body_1:
	; source: examples/do_while.c:43
	MOV      R0, #0              
	MOV      [R15+#4], R0        ; j = R0
.Laninhado_do_body_3:
	; source: examples/do_while.c:45
	MOV      R0, [R15+#4]        ; R0 = j
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#4], R2        ; j = R2
	; source: examples/do_while.c:46
	MOV      R0, [R15+#4]        ; R0 = j
	MOV      R1, #2              
	CMP      R0, R1              
	JMPR     cc_Z, .Laninhado_cmp_true_7
	MOV      R2, #0              
	JMPR     cc_UC, .Laninhado_cmp_end_7
.Laninhado_cmp_true_7:
	MOV      R2, #1              
.Laninhado_cmp_end_7:
	; source: examples/do_while.c:47
	CMP      R2, #0              
	JMPR     cc_NZ, .Laninhado_if_then_6
	JMPR     cc_UC, .Laninhado_if_end_8
.Laninhado_if_then_6:
	JMPR     cc_UC, .Laninhado_do_cond_4
.Laninhado_if_end_8:
	MOV      R0, [R15+#2]        ; R0 = total
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#2], R2        ; total = R2
.Laninhado_do_cond_4:
	; source: examples/do_while.c:48
	MOV      R0, [R15+#4]        ; R0 = j
	MOV      R1, #3              
	CMP      R0, R1              
	JMPR     cc_C, .Laninhado_cmp_true_8
	MOV      R2, #0              
	JMPR     cc_UC, .Laninhado_cmp_end_8
.Laninhado_cmp_true_8:
	MOV      R2, #1              
.Laninhado_cmp_end_8:
	CMP      R2, #0              
	JMPR     cc_NZ, .Laninhado_do_body_3
.Laninhado_do_end_5:
	; source: examples/do_while.c:49
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #1              
	MOV      R2, R0              
	SUB      R2, R1              
	MOV      [R15+#0], R2        ; n = R2
	JMPR     cc_UC, .Laninhado_while_cond_0
.Laninhado_while_end_2:
	; source: examples/do_while.c:51
	MOV      R0, #0              
	; source: examples/do_while.c:60
	MOV      [R15+#6], R0        ; f = R0
.Laninhado_for_cond_9:
	; source: examples/do_while.c:51
	MOV      R0, [R15+#6]        ; R0 = f
	MOV      R1, #4              
	CMP      R0, R1              
	JMPR     cc_C, .Laninhado_cmp_true_9
	MOV      R2, #0              
	JMPR     cc_UC, .Laninhado_cmp_end_9
.Laninhado_cmp_true_9:
	MOV      R2, #1              
.Laninhado_cmp_end_9:
	CMP      R2, #0              
	JMPR     cc_NZ, .Laninhado_for_body_10
	JMPR     cc_UC, .Laninhado_for_end_12
.Laninhado_for_body_10:
.Laninhado_do_body_13:
	; source: examples/do_while.c:53
	MOV      R0, [R15+#2]        ; R0 = total
	MOV      R1, [R15+#6]        ; R1 = f
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#2], R2        ; total = R2
.Laninhado_do_body_16:
	; source: examples/do_while.c:55
	MOV      R0, [R15+#2]        ; R0 = total
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#2], R2        ; total = R2
	; source: examples/do_while.c:56
	MOV      R0, [R15+#2]        ; R0 = total
	MOV      R1, #100            
	CMP      R0, R1              
	JMPR     cc_UGT, .Laninhado_cmp_true_10
	MOV      R2, #0              
	JMPR     cc_UC, .Laninhado_cmp_end_10
.Laninhado_cmp_true_10:
	MOV      R2, #1              
.Laninhado_cmp_end_10:
	; source: examples/do_while.c:57
	CMP      R2, #0              
	JMPR     cc_NZ, .Laninhado_if_then_19
	JMPR     cc_UC, .Laninhado_if_end_21
.Laninhado_if_then_19:
	JMPR     cc_UC, .Laninhado_do_end_18
.Laninhado_if_end_21:
.Laninhado_do_cond_17:
	MOV      R0, [R15+#2]        ; R0 = total
	MOV      R1, #1              
	MOV      R2, R0              
	AND      R2, R1              
	CMP      R2, #0              
	JMPR     cc_NZ, .Laninhado_do_body_16
.Laninhado_do_end_18:
.Laninhado_do_cond_14:
	; source: examples/do_while.c:58
	MOV      R0, #0              
	CMP      R0, #0              
	JMPR     cc_NZ, .Laninhado_do_body_13
.Laninhado_do_end_15:
	; source: examples/do_while.c:59
	MOV      R0, [R15+#6]        ; R0 = f
	MOV      R1, #2              
	CMP      R0, R1              
	JMPR     cc_Z, .Laninhado_cmp_true_11
	MOV      R2, #0              
	JMPR     cc_UC, .Laninhado_cmp_end_11
.Laninhado_cmp_true_11:
	MOV      R2, #1              
.Laninhado_cmp_end_11:
	; source: examples/do_while.c:60
	CMP      R2, #0              
	JMPR     cc_NZ, .Laninhado_if_then_22
	JMPR     cc_UC, .Laninhado_if_end_24
.Laninhado_if_then_22:
	JMPR     cc_UC, .Laninhado_for_post_11
.Laninhado_if_end_24:
.Laninhado_for_post_11:
	; source: examples/do_while.c:51
	MOV      R0, [R15+#6]        ; R0 = f
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#6], R2        ; f = R2
	JMPR     cc_UC, .Laninhado_for_cond_9
.Laninhado_for_end_12:
	; source: examples/do_while.c:61
	MOV      R0, [R15+#2]        ; R0 = total
	ADD      SP, #8              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

