; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
SRC		EQU	02000H		; @ram @0x2000 (uint16_t)
OUT:		DS	2		; uint16_t

	.section .text
	.global farread_global

farread_global:
	PUSH     R15                 ; save caller's frame pointer
	MOV      R15, SP             ; establish frame pointer
	; source: examples/farread_global.c:16
	MOV      R0, #0              
	MOV      R1, #8192           
	EXTP     R0, #1              ; page override for the next instruction only
	MOV      R2, [R1]            ; far word (page-relative)
	MOV      OUT, R2             ; OUT = R2
	POP      R15                 ; restore caller's frame pointer
	RET                          
