; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global fatorial

fatorial:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'n'
	; source: examples/fatorial.c:3
	MOV      R0, #1              
	MOV      [R15+#2], R0        ; result = R0
	; source: examples/fatorial.c:5
	MOV      R0, #2              
	MOV      [R15+#4], R0        ; i = R0
.Lfatorial_for_cond_0:
	MOV      R0, [R15+#4]        ; R0 = i
	MOV      R1, [R15+#0]        ; R1 = n
	CMP      R0, R1              
	JMPR     cc_ULE, .Lfatorial_cmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lfatorial_cmp_end_1
.Lfatorial_cmp_true_1:
	MOV      R2, #1              
.Lfatorial_cmp_end_1:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lfatorial_for_body_1
	JMPR     cc_UC, .Lfatorial_for_end_3
.Lfatorial_for_body_1:
	; source: examples/fatorial.c:6
	MOV      R0, [R15+#2]        ; R0 = result
	MOV      R1, [R15+#4]        ; R1 = i
	MULU     R0, R1              
	MOV      R2, MDL             ; low word of MDL:MDH product
	MOV      [R15+#2], R2        ; result = R2
.Lfatorial_for_post_2:
	; source: examples/fatorial.c:5
	MOV      R0, [R15+#4]        ; R0 = i
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#4], R2        ; i = R2
	JMPR     cc_UC, .Lfatorial_for_cond_0
.Lfatorial_for_end_3:
	; source: examples/fatorial.c:8
	MOV      R0, [R15+#2]        ; R0 = result
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

