; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global fatorial_rec

fatorial_rec:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'n'
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/fatorial_rec.c:3
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #1              
	CMP      R0, R1              
	JMPR     cc_ULE, .Lcmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lcmp_end_1  
.Lcmp_true_1:
	MOV      R2, #1              
.Lcmp_end_1:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/fatorial_rec.c:5
	CMP      R2, #0              
	JMPR     cc_NZ, .Lfatorial_rec_if_then_0
	JMPR     cc_UC, .Lfatorial_rec_if_end_2
.Lfatorial_rec_if_then_0:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/fatorial_rec.c:4
	MOV      R0, #1              
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Lfatorial_rec_if_end_2:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/fatorial_rec.c:5
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, [R15+#0]        ; R1 = n
	MOV      R2, #1              
	MOV      R3, R1              
	SUB      R3, R2              
	MOV      R4, R3              
	CALLR    fatorial_rec        
	MOV      R1, R0              ; function result
	MULU     R0, R1              
	MOV      R2, MDL             ; low word of MDL:MDH product
	MOV      R0, R2              ; return value
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
