; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global fatorial_rec

fatorial_rec:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'n'
	; source: examples/fatorial_rec.c:3
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #1              
	CMP      R0, R1              
	JMPR     cc_ULE, .Lfatorial_rec_cmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lfatorial_rec_cmp_end_1
.Lfatorial_rec_cmp_true_1:
	MOV      R2, #1              
.Lfatorial_rec_cmp_end_1:
	; source: examples/fatorial_rec.c:5
	CMP      R2, #0              
	JMPR     cc_NZ, .Lfatorial_rec_if_then_0
	JMPR     cc_UC, .Lfatorial_rec_if_end_2
.Lfatorial_rec_if_then_0:
	; source: examples/fatorial_rec.c:4
	MOV      R0, #1              
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Lfatorial_rec_if_end_2:
	; source: examples/fatorial_rec.c:5
	MOV      R11, [R15+#0]       ; R11 = n
	MOV      [R15+#2], R11       
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #1              
	MOV      R2, R0              
	SUB      R2, R1              
	MOV      R4, R2              
	CALLR    fatorial_rec        
	MOV      R11, [R15+#2]       ; reload spilled value
	MULU     R11, R0             
	MOV      R1, MDL             ; low word of MDL:MDH product
	MOV      R0, R1              ; return value
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

