; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
calib_1356		EQU	01356H		; @ram @0x1356 (uint8_t)
tab_w_1358		EQU	01358H		; @ram @0x1358 (uint16_t)
tab		EQU	0E0B3H		; @ram @0xE0B3 (array)
idx		EQU	0E09FH		; @ram @0xE09F (uint8_t)

	.section .text
	.global le_byte
	.global escreve_byte
	.global le_word
	.global escreve_word

le_byte:
	PUSH     R15                 ; save caller's frame pointer
	MOV      R15, SP             ; establish frame pointer
	; source: examples/index_scalar_ram.c:12
	MOV      R0, #calib_1356     ; near address of global
	MOV      R1, #tab            ; near address of global
	MOVB     R2, idx             ; R2 = idx
	AND      R2, #0x00FF         
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     R1, [R3]            
	AND      R1, #0x00FF         
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	POP      R15                 ; restore caller's frame pointer
	RET                          

escreve_byte:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOVB     [R15+#0], R4        ; spill incoming parameter 'v'
	; source: examples/index_scalar_ram.c:13
	MOVB     R0, [R15+#0]        ; R0 = v
	AND      R0, #0x00FF         
	MOV      R1, #calib_1356     ; near address of global
	MOVB     R2, idx             ; R2 = idx
	AND      R2, #0x00FF         
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     [R3], R0            
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

le_word:
	PUSH     R15                 ; save caller's frame pointer
	MOV      R15, SP             ; establish frame pointer
	; source: examples/index_scalar_ram.c:14
	MOV      R0, #tab_w_1358     ; near address of global
	MOVB     R1, idx             ; R1 = idx
	AND      R1, #0x00FF         
	MOV      R2, #2              
	MULU     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      R0, [R1]            
	POP      R15                 ; restore caller's frame pointer
	RET                          

escreve_word:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'v'
	; source: examples/index_scalar_ram.c:15
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, #tab_w_1358     ; near address of global
	MOVB     R2, idx             ; R2 = idx
	AND      R2, #0x00FF         
	MOV      R3, #2              
	MULU     R2, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R2, R1              
	ADD      R2, R8              
	MOV      [R2], R0            
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

