; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
a		EQU	0E7F8H		; @ram @0xE7F8 (uint8_t)
b		EQU	0E09AH		; @ram @0xE09A (uint8_t)
c		EQU	0E194H		; @ram @0xE194 (uint8_t)
d		EQU	0E0D8H		; @ram @0xE0D8 (uint8_t)

	.section .text
	.global or3
	.global and3
	.global mistura
	.global associacoes
	.global or4_atribuicao
	.global or3_while

or3:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/logic_chain3.c:18
	MOV      R0, #0              
	MOVB     [R15+#0], R0        ; r = R0
	; source: examples/logic_chain3.c:19
	MOVB     R0, a               ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #16             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor3_cmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lor3_cmp_end_1
.Lor3_cmp_true_1:
	MOV      R2, #1              
.Lor3_cmp_end_1:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor3_logic_true_8
.Lor3_or_rhs_7:
	MOVB     R0, b               ; R0 = b
	AND      R0, #0x00FF         
	MOV      R1, #32             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor3_cmp_true_2
	MOV      R2, #0              
	JMPR     cc_UC, .Lor3_cmp_end_2
.Lor3_cmp_true_2:
	MOV      R2, #1              
.Lor3_cmp_end_2:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor3_logic_true_8
	JMPR     cc_UC, .Lor3_logic_false_9
.Lor3_logic_true_8:
	MOV      R0, #1              
	JMPR     cc_UC, .Lor3_logic_end_10
.Lor3_logic_false_9:
	MOV      R0, #0              
.Lor3_logic_end_10:
	CMP      R0, #0              
	JMPR     cc_NZ, .Lor3_logic_true_4
.Lor3_or_rhs_3:
	MOVB     R0, c               ; R0 = c
	AND      R0, #0x00FF         
	MOV      R1, #48             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor3_cmp_true_3
	MOV      R2, #0              
	JMPR     cc_UC, .Lor3_cmp_end_3
.Lor3_cmp_true_3:
	MOV      R2, #1              
.Lor3_cmp_end_3:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor3_logic_true_4
	JMPR     cc_UC, .Lor3_logic_false_5
.Lor3_logic_true_4:
	MOV      R0, #1              
	JMPR     cc_UC, .Lor3_logic_end_6
.Lor3_logic_false_5:
	MOV      R0, #0              
.Lor3_logic_end_6:
	; source: examples/logic_chain3.c:20
	CMP      R0, #0              
	JMPR     cc_NZ, .Lor3_if_then_0
	JMPR     cc_UC, .Lor3_if_end_2
.Lor3_if_then_0:
	; source: examples/logic_chain3.c:19
	MOV      R0, #1              
	MOVB     [R15+#0], R0        ; r = R0
.Lor3_if_end_2:
	; source: examples/logic_chain3.c:20
	MOVB     R0, [R15+#0]        ; R0 = r
	AND      R0, #0x00FF         
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

and3:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/logic_chain3.c:25
	MOV      R0, #0              
	MOVB     [R15+#0], R0        ; r = R0
	; source: examples/logic_chain3.c:26
	MOVB     R0, a               ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #16             
	CMP      R0, R1              
	JMPR     cc_NC, .Land3_cmp_true_4
	MOV      R2, #0              
	JMPR     cc_UC, .Land3_cmp_end_4
.Land3_cmp_true_4:
	MOV      R2, #1              
.Land3_cmp_end_4:
	CMP      R2, #0              
	JMPR     cc_NZ, .Land3_and_rhs_7
	JMPR     cc_UC, .Land3_logic_false_9
.Land3_and_rhs_7:
	MOVB     R0, b               ; R0 = b
	AND      R0, #0x00FF         
	MOV      R1, #32             
	CMP      R0, R1              
	JMPR     cc_NC, .Land3_cmp_true_5
	MOV      R2, #0              
	JMPR     cc_UC, .Land3_cmp_end_5
.Land3_cmp_true_5:
	MOV      R2, #1              
.Land3_cmp_end_5:
	CMP      R2, #0              
	JMPR     cc_NZ, .Land3_logic_true_8
	JMPR     cc_UC, .Land3_logic_false_9
.Land3_logic_true_8:
	MOV      R0, #1              
	JMPR     cc_UC, .Land3_logic_end_10
.Land3_logic_false_9:
	MOV      R0, #0              
.Land3_logic_end_10:
	CMP      R0, #0              
	JMPR     cc_NZ, .Land3_and_rhs_3
	JMPR     cc_UC, .Land3_logic_false_5
.Land3_and_rhs_3:
	MOVB     R0, c               ; R0 = c
	AND      R0, #0x00FF         
	MOV      R1, #48             
	CMP      R0, R1              
	JMPR     cc_NC, .Land3_cmp_true_6
	MOV      R2, #0              
	JMPR     cc_UC, .Land3_cmp_end_6
.Land3_cmp_true_6:
	MOV      R2, #1              
.Land3_cmp_end_6:
	CMP      R2, #0              
	JMPR     cc_NZ, .Land3_logic_true_4
	JMPR     cc_UC, .Land3_logic_false_5
.Land3_logic_true_4:
	MOV      R0, #1              
	JMPR     cc_UC, .Land3_logic_end_6
.Land3_logic_false_5:
	MOV      R0, #0              
.Land3_logic_end_6:
	; source: examples/logic_chain3.c:27
	CMP      R0, #0              
	JMPR     cc_NZ, .Land3_if_then_0
	JMPR     cc_UC, .Land3_if_end_2
.Land3_if_then_0:
	; source: examples/logic_chain3.c:26
	MOV      R0, #1              
	MOVB     [R15+#0], R0        ; r = R0
.Land3_if_end_2:
	; source: examples/logic_chain3.c:27
	MOVB     R0, [R15+#0]        ; R0 = r
	AND      R0, #0x00FF         
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

mistura:
	PUSH     R15                 ; save caller's frame pointer
	MOV      R15, SP             ; establish frame pointer
	; source: examples/logic_chain3.c:32
	MOVB     R0, a               ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #16             
	CMP      R0, R1              
	JMPR     cc_NC, .Lmistura_cmp_true_7
	MOV      R2, #0              
	JMPR     cc_UC, .Lmistura_cmp_end_7
.Lmistura_cmp_true_7:
	MOV      R2, #1              
.Lmistura_cmp_end_7:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lmistura_logic_true_1
.Lmistura_or_rhs_0:
	MOVB     R0, b               ; R0 = b
	AND      R0, #0x00FF         
	MOV      R1, #32             
	CMP      R0, R1              
	JMPR     cc_NC, .Lmistura_cmp_true_8
	MOV      R2, #0              
	JMPR     cc_UC, .Lmistura_cmp_end_8
.Lmistura_cmp_true_8:
	MOV      R2, #1              
.Lmistura_cmp_end_8:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lmistura_and_rhs_4
	JMPR     cc_UC, .Lmistura_logic_false_6
.Lmistura_and_rhs_4:
	MOVB     R0, c               ; R0 = c
	AND      R0, #0x00FF         
	MOV      R1, #48             
	CMP      R0, R1              
	JMPR     cc_NC, .Lmistura_cmp_true_9
	MOV      R2, #0              
	JMPR     cc_UC, .Lmistura_cmp_end_9
.Lmistura_cmp_true_9:
	MOV      R2, #1              
.Lmistura_cmp_end_9:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lmistura_logic_true_5
	JMPR     cc_UC, .Lmistura_logic_false_6
.Lmistura_logic_true_5:
	MOV      R0, #1              
	JMPR     cc_UC, .Lmistura_logic_end_7
.Lmistura_logic_false_6:
	MOV      R0, #0              
.Lmistura_logic_end_7:
	CMP      R0, #0              
	JMPR     cc_NZ, .Lmistura_logic_true_1
	JMPR     cc_UC, .Lmistura_logic_false_2
.Lmistura_logic_true_1:
	MOV      R0, #1              
	JMPR     cc_UC, .Lmistura_logic_end_3
.Lmistura_logic_false_2:
	MOV      R0, #0              
.Lmistura_logic_end_3:
	POP      R15                 ; restore caller's frame pointer
	RET                          

associacoes:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/logic_chain3.c:37
	MOVB     R0, a               ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #16             
	CMP      R0, R1              
	JMPR     cc_NC, .Lassociacoes_cmp_true_10
	MOV      R2, #0              
	JMPR     cc_UC, .Lassociacoes_cmp_end_10
.Lassociacoes_cmp_true_10:
	MOV      R2, #1              
.Lassociacoes_cmp_end_10:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_5
.Lassociacoes_or_rhs_4:
	MOVB     R0, b               ; R0 = b
	AND      R0, #0x00FF         
	MOV      R1, #32             
	CMP      R0, R1              
	JMPR     cc_NC, .Lassociacoes_cmp_true_11
	MOV      R2, #0              
	JMPR     cc_UC, .Lassociacoes_cmp_end_11
.Lassociacoes_cmp_true_11:
	MOV      R2, #1              
.Lassociacoes_cmp_end_11:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_5
	JMPR     cc_UC, .Lassociacoes_logic_false_6
.Lassociacoes_logic_true_5:
	MOV      R0, #1              
	JMPR     cc_UC, .Lassociacoes_logic_end_7
.Lassociacoes_logic_false_6:
	MOV      R0, #0              
.Lassociacoes_logic_end_7:
	CMP      R0, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_1
.Lassociacoes_or_rhs_0:
	MOVB     R0, c               ; R0 = c
	AND      R0, #0x00FF         
	MOV      R1, #48             
	CMP      R0, R1              
	JMPR     cc_NC, .Lassociacoes_cmp_true_12
	MOV      R2, #0              
	JMPR     cc_UC, .Lassociacoes_cmp_end_12
.Lassociacoes_cmp_true_12:
	MOV      R2, #1              
.Lassociacoes_cmp_end_12:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_1
	JMPR     cc_UC, .Lassociacoes_logic_false_2
.Lassociacoes_logic_true_1:
	MOV      R0, #1              
	JMPR     cc_UC, .Lassociacoes_logic_end_3
.Lassociacoes_logic_false_2:
	MOV      R0, #0              
.Lassociacoes_logic_end_3:
	MOV      [R15+#0], R0        ; r = R0
	; source: examples/logic_chain3.c:38
	MOV      R0, [R15+#0]        ; R0 = r
	MOVB     R1, a               ; R1 = a
	AND      R1, #0x00FF         
	MOV      R2, #16             
	CMP      R1, R2              
	JMPR     cc_NC, .Lassociacoes_cmp_true_13
	MOV      R3, #0              
	JMPR     cc_UC, .Lassociacoes_cmp_end_13
.Lassociacoes_cmp_true_13:
	MOV      R3, #1              
.Lassociacoes_cmp_end_13:
	CMP      R3, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_9
.Lassociacoes_or_rhs_8:
	MOVB     R1, b               ; R1 = b
	AND      R1, #0x00FF         
	MOV      R2, #32             
	CMP      R1, R2              
	JMPR     cc_NC, .Lassociacoes_cmp_true_14
	MOV      R3, #0              
	JMPR     cc_UC, .Lassociacoes_cmp_end_14
.Lassociacoes_cmp_true_14:
	MOV      R3, #1              
.Lassociacoes_cmp_end_14:
	CMP      R3, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_13
.Lassociacoes_or_rhs_12:
	MOVB     R1, c               ; R1 = c
	AND      R1, #0x00FF         
	MOV      R2, #48             
	CMP      R1, R2              
	JMPR     cc_NC, .Lassociacoes_cmp_true_15
	MOV      R3, #0              
	JMPR     cc_UC, .Lassociacoes_cmp_end_15
.Lassociacoes_cmp_true_15:
	MOV      R3, #1              
.Lassociacoes_cmp_end_15:
	CMP      R3, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_13
	JMPR     cc_UC, .Lassociacoes_logic_false_14
.Lassociacoes_logic_true_13:
	MOV      R1, #1              
	JMPR     cc_UC, .Lassociacoes_logic_end_15
.Lassociacoes_logic_false_14:
	MOV      R1, #0              
.Lassociacoes_logic_end_15:
	CMP      R1, #0              
	JMPR     cc_NZ, .Lassociacoes_logic_true_9
	JMPR     cc_UC, .Lassociacoes_logic_false_10
.Lassociacoes_logic_true_9:
	MOV      R1, #1              
	JMPR     cc_UC, .Lassociacoes_logic_end_11
.Lassociacoes_logic_false_10:
	MOV      R1, #0              
.Lassociacoes_logic_end_11:
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#0], R2        ; r = R2
	; source: examples/logic_chain3.c:39
	MOV      R0, [R15+#0]        ; R0 = r
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

or4_atribuicao:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/logic_chain3.c:44
	MOVB     R0, a               ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #16             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor4_atribuicao_cmp_true_16
	MOV      R2, #0              
	JMPR     cc_UC, .Lor4_atribuicao_cmp_end_16
.Lor4_atribuicao_cmp_true_16:
	MOV      R2, #1              
.Lor4_atribuicao_cmp_end_16:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor4_atribuicao_logic_true_9
.Lor4_atribuicao_or_rhs_8:
	MOVB     R0, b               ; R0 = b
	AND      R0, #0x00FF         
	MOV      R1, #32             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor4_atribuicao_cmp_true_17
	MOV      R2, #0              
	JMPR     cc_UC, .Lor4_atribuicao_cmp_end_17
.Lor4_atribuicao_cmp_true_17:
	MOV      R2, #1              
.Lor4_atribuicao_cmp_end_17:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor4_atribuicao_logic_true_9
	JMPR     cc_UC, .Lor4_atribuicao_logic_false_10
.Lor4_atribuicao_logic_true_9:
	MOV      R0, #1              
	JMPR     cc_UC, .Lor4_atribuicao_logic_end_11
.Lor4_atribuicao_logic_false_10:
	MOV      R0, #0              
.Lor4_atribuicao_logic_end_11:
	CMP      R0, #0              
	JMPR     cc_NZ, .Lor4_atribuicao_logic_true_5
.Lor4_atribuicao_or_rhs_4:
	MOVB     R0, c               ; R0 = c
	AND      R0, #0x00FF         
	MOV      R1, #48             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor4_atribuicao_cmp_true_18
	MOV      R2, #0              
	JMPR     cc_UC, .Lor4_atribuicao_cmp_end_18
.Lor4_atribuicao_cmp_true_18:
	MOV      R2, #1              
.Lor4_atribuicao_cmp_end_18:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor4_atribuicao_logic_true_5
	JMPR     cc_UC, .Lor4_atribuicao_logic_false_6
.Lor4_atribuicao_logic_true_5:
	MOV      R0, #1              
	JMPR     cc_UC, .Lor4_atribuicao_logic_end_7
.Lor4_atribuicao_logic_false_6:
	MOV      R0, #0              
.Lor4_atribuicao_logic_end_7:
	CMP      R0, #0              
	JMPR     cc_NZ, .Lor4_atribuicao_logic_true_1
.Lor4_atribuicao_or_rhs_0:
	MOVB     R0, d               ; R0 = d
	AND      R0, #0x00FF         
	MOV      R1, #64             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor4_atribuicao_cmp_true_19
	MOV      R2, #0              
	JMPR     cc_UC, .Lor4_atribuicao_cmp_end_19
.Lor4_atribuicao_cmp_true_19:
	MOV      R2, #1              
.Lor4_atribuicao_cmp_end_19:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor4_atribuicao_logic_true_1
	JMPR     cc_UC, .Lor4_atribuicao_logic_false_2
.Lor4_atribuicao_logic_true_1:
	MOV      R0, #1              
	JMPR     cc_UC, .Lor4_atribuicao_logic_end_3
.Lor4_atribuicao_logic_false_2:
	MOV      R0, #0              
.Lor4_atribuicao_logic_end_3:
	MOV      [R15+#0], R0        ; r = R0
	; source: examples/logic_chain3.c:45
	MOV      R0, [R15+#0]        ; R0 = r
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

or3_while:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/logic_chain3.c:50
	MOV      R0, #0              
	MOV      [R15+#0], R0        ; n = R0
.Lor3_while_while_cond_0:
	; source: examples/logic_chain3.c:51
	MOVB     R0, a               ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #16             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor3_while_cmp_true_20
	MOV      R2, #0              
	JMPR     cc_UC, .Lor3_while_cmp_end_20
.Lor3_while_cmp_true_20:
	MOV      R2, #1              
.Lor3_while_cmp_end_20:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor3_while_logic_true_8
.Lor3_while_or_rhs_7:
	MOVB     R0, b               ; R0 = b
	AND      R0, #0x00FF         
	MOV      R1, #32             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor3_while_cmp_true_21
	MOV      R2, #0              
	JMPR     cc_UC, .Lor3_while_cmp_end_21
.Lor3_while_cmp_true_21:
	MOV      R2, #1              
.Lor3_while_cmp_end_21:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor3_while_logic_true_8
	JMPR     cc_UC, .Lor3_while_logic_false_9
.Lor3_while_logic_true_8:
	MOV      R0, #1              
	JMPR     cc_UC, .Lor3_while_logic_end_10
.Lor3_while_logic_false_9:
	MOV      R0, #0              
.Lor3_while_logic_end_10:
	CMP      R0, #0              
	JMPR     cc_NZ, .Lor3_while_logic_true_4
.Lor3_while_or_rhs_3:
	MOVB     R0, c               ; R0 = c
	AND      R0, #0x00FF         
	MOV      R1, #48             
	CMP      R0, R1              
	JMPR     cc_NC, .Lor3_while_cmp_true_22
	MOV      R2, #0              
	JMPR     cc_UC, .Lor3_while_cmp_end_22
.Lor3_while_cmp_true_22:
	MOV      R2, #1              
.Lor3_while_cmp_end_22:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lor3_while_logic_true_4
	JMPR     cc_UC, .Lor3_while_logic_false_5
.Lor3_while_logic_true_4:
	MOV      R0, #1              
	JMPR     cc_UC, .Lor3_while_logic_end_6
.Lor3_while_logic_false_5:
	MOV      R0, #0              
.Lor3_while_logic_end_6:
	CMP      R0, #0              
	JMPR     cc_NZ, .Lor3_while_while_body_1
	JMPR     cc_UC, .Lor3_while_while_end_2
.Lor3_while_while_body_1:
	MOV      R0, [R15+#0]        ; R0 = n
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#0], R2        ; n = R2
	JMPR     cc_UC, .Lor3_while_while_cond_0
.Lor3_while_while_end_2:
	; source: examples/logic_chain3.c:52
	MOV      R0, [R15+#0]        ; R0 = n
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

