; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global max_vetor

max_vetor:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #8              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'v'
	MOV      [R15+#2], R5        ; spill incoming parameter 'n'
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/max_vetor.c:3
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, #0              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOV      [R15+#4], R0        ; maior = R0
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/max_vetor.c:5
	MOV      R0, #1              
	MOV      [R15+#6], R0        ; i = R0
.Lmax_vetor_for_cond_0:
	MOV      R0, [R15+#6]        ; R0 = i
	MOV      R1, [R15+#2]        ; R1 = n
	CMP      R0, R1              
	JMPR     cc_C, .Lcmp_true_1  
	MOV      R2, #0              
	JMPR     cc_UC, .Lcmp_end_1  
.Lcmp_true_1:
	MOV      R2, #1              
.Lcmp_end_1:
	CMP      R2, #0              
	JMPR     cc_NZ, .Lmax_vetor_for_body_1
	JMPR     cc_UC, .Lmax_vetor_for_end_3
.Lmax_vetor_for_body_1:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/max_vetor.c:6
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, [R15+#6]        ; R1 = i
	MOV      R2, #2              
	MULU     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      R0, [R1]            
	MOV      R1, [R15+#4]        ; R1 = maior
	CMP      R0, R1              
	JMPR     cc_UGT, .Lcmp_true_2
	MOV      R2, #0              
	JMPR     cc_UC, .Lcmp_end_2  
.Lcmp_true_2:
	MOV      R2, #1              
.Lcmp_end_2:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/max_vetor.c:8
	CMP      R2, #0              
	JMPR     cc_NZ, .Lmax_vetor_if_then_4
	JMPR     cc_UC, .Lmax_vetor_if_end_6
.Lmax_vetor_if_then_4:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/max_vetor.c:7
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, [R15+#6]        ; R1 = i
	MOV      R2, #2              
	MULU     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      R0, [R1]            
	MOV      [R15+#4], R0        ; maior = R0
.Lmax_vetor_if_end_6:
.Lmax_vetor_for_post_2:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/max_vetor.c:5
	MOV      R0, [R15+#6]        ; R0 = i
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#6], R2        ; i = R2
	JMPR     cc_UC, .Lmax_vetor_for_cond_0
.Lmax_vetor_for_end_3:
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/max_vetor.c:9
	MOV      R0, [R15+#4]        ; R0 = maior
	ADD      SP, #8              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
