; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
tabela:		DS	16		; array

	.section .text
	.global le_segundo_elemento

le_segundo_elemento:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/pointer_arith_scaling_array.c:3
	MOV      R0, #tabela         ; near address of global
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#0], R2        ; p = R2
	; source: examples/pointer_arith_scaling_array.c:4
	MOV      R0, [R15+#0]        ; R0 = p
	MOV      R1, [R0]            
	MOV      R0, R1              ; return value
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
