; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global bug9
	.global bug16
	.global bug16v
	.global u16
	.global s8

bug9:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOVB     [R15+#0], R4        ; spill incoming parameter 'd'
	; source: examples/sign_cast_shift.c:10
	MOVB     R0, [R15+#0]        ; R0 = d
	AND      R0, #0x00FF         
	MOV      R1, R0              
	SHL      R1, #8              ; narrow to signed byte: shift byte to high half
	ASHR     R1, #8              ; ...then arithmetic-shift back, replicating the sign bit
	MOV      R0, #0              
	CMP      R1, R0              
	JMPR     cc_SGT, .Lbug9_cmp_true_1
	MOV      R2, #0              
	JMPR     cc_UC, .Lbug9_cmp_end_1
.Lbug9_cmp_true_1:
	MOV      R2, #1              
.Lbug9_cmp_end_1:
	; source: examples/sign_cast_shift.c:13
	CMP      R2, #0              
	JMPR     cc_NZ, .Lbug9_if_then_0
	JMPR     cc_UC, .Lbug9_if_end_2
.Lbug9_if_then_0:
	; source: examples/sign_cast_shift.c:11
	MOV      R0, #1              
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Lbug9_if_end_2:
	; source: examples/sign_cast_shift.c:13
	MOV      R0, #0              
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug16:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'x'
	; source: examples/sign_cast_shift.c:17
	MOV      R0, [R15+#0]        ; R0 = x
	MOV      R1, #6              
	MOV      R2, R0              
	ASHR     R2, R1              
	MOV      R0, R2              ; return value
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug16v:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'x'
	MOV      [R15+#2], R5        ; spill incoming parameter 'n'
	; source: examples/sign_cast_shift.c:21
	MOV      R0, [R15+#0]        ; R0 = x
	MOV      [R15+#4], R0        ; s = R0
	; source: examples/sign_cast_shift.c:22
	MOV      R0, [R15+#4]        ; R0 = s
	MOV      R1, [R15+#2]        ; R1 = n
	MOV      R2, R0              
	ASHR     R2, R1              
	MOV      R0, R2              ; return value
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

u16:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'x'
	MOV      [R15+#2], R5        ; spill incoming parameter 'n'
	; source: examples/sign_cast_shift.c:26
	MOV      R0, [R15+#0]        ; R0 = x
	MOV      R1, #3              
	MOV      R2, R0              
	SHR      R2, R1              
	MOV      R0, [R15+#0]        ; R0 = x
	MOV      R1, [R15+#2]        ; R1 = n
	MOV      R3, R0              
	SHR      R3, R1              
	MOV      R0, R2              
	ADD      R0, R3              
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

s8:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOVB     [R15+#0], R4        ; spill incoming parameter 'x'
	; source: examples/sign_cast_shift.c:30
	MOVB     R0, [R15+#0]        ; R0 = x
	SHL      R0, #8              ; sign-extend: byte to high byte
	ASHR     R0, #8              ; sign-extend: replicate sign bit back down
	MOV      R1, #1              
	MOV      R2, R0              
	ASHR     R2, R1              
	MOV      R0, #1              
	MOV      R1, R2              
	ASHR     R1, R0              
	MOV      R0, R1              ; return value
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

