; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global sum_point
	.global manhattan

sum_point:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'p'
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/struct_basic.c:8
	MOV      R0, [R15+#0]        ; R0 = p
	MOV      R1, [R0]            
	MOV      R0, [R15+#0]        ; R0 = p
	MOV      R2, #2              
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, [R3]            
	MOV      R2, R1              
	ADD      R2, R0              
	MOV      R0, R2              ; return value
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

manhattan:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #8              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'a'
	MOV      [R15+#2], R5        ; spill incoming parameter 'b'
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/struct_basic.c:14
	MOV      R0, [R15+#0]        ; R0 = a
	MOV      R1, [R0]            
	MOV      R0, [R15+#2]        ; R0 = b
	MOV      R2, [R0]            
	MOV      R0, R1              
	SUB      R0, R2              
	MOV      R1, R15             
	ADD      R1, #4              
	MOV      [R1], R0            
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/struct_basic.c:15
	MOV      R0, [R15+#0]        ; R0 = a
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOV      R1, [R15+#2]        ; R1 = b
	MOV      R2, #2              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R3]            
	MOV      R2, R0              
	SUB      R2, R1              
	MOV      R0, R15             
	ADD      R0, #4              
	MOV      R1, #2              
	MOV      R3, R0              
	ADD      R3, R1              
	MOV      [R3], R2            
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/struct_basic.c:16
	MOV      R0, R15             
	ADD      R0, #4              
	MOV      R4, R0              
	CALLR    sum_point           
	MOV      R1, R0              ; function result
	MOV      R0, R1              ; return value
	ADD      SP, #8              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

