; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .bss
g_par:		DS	4		; par_bytes_t
g_misto:		DS	12		; misto_t
g_cores:		DS	9		; array
g_aninhada:		DS	10		; aninhada_t
g_reg:		DS	4		; reg_t
ram_par		EQU	0E100H		; @ram @0xE100 (par_bytes_t)
ram_tab		EQU	0E200H		; @ram @0xE200 (array)
g_init:		DW	8721,17459		; par_bytes_t, inicializado
g_init_misto:		DW	1,770,1284,6,2055,2569		; misto_t, inicializado
g_init_cores:		DW	513,1027,1541		; array, inicializado

	.section .text
	.global bug13
	.global ponto_global
	.global local
	.global array_de_struct
	.global aninhada
	.global uniao
	.global copia

bug13:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'p'
	; source: examples/struct_byte_layout.c:54
	MOV      R0, [R15+#0]        ; R0 = p
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, [R15+#0]        ; R1 = p
	MOV      R2, #2              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R3]            
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, R2              ; return value
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

ponto_global:
	PUSH     R15                 ; save caller's frame pointer
	MOV      R15, SP             ; establish frame pointer
	; source: examples/struct_byte_layout.c:60
	MOV      R0, #18             
	MOV      R1, #g_par          ; near address of global
	MOV      R2, #1              
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     [R3], R0            
	; source: examples/struct_byte_layout.c:61
	MOV      R0, #g_par          ; near address of global
	MOVB     R1, [R0]            
	AND      R1, #0x00FF         
	MOV      R0, #g_misto        ; near address of global
	MOV      R2, #6              
	MOV      R3, R0              
	ADD      R3, R2              
	MOVB     [R3], R1            
	; source: examples/struct_byte_layout.c:62
	MOV      R0, #258            
	MOV      R1, #g_misto        ; near address of global
	MOV      R2, #2              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      [R3], R0            
	; source: examples/struct_byte_layout.c:63
	MOV      R0, #g_misto        ; near address of global
	MOV      R1, #5              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #ram_par        ; near address of global
	MOV      R2, #1              
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     [R3], R0            
	; source: examples/struct_byte_layout.c:64
	MOV      R0, #ram_par        ; near address of global
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	POP      R15                 ; restore caller's frame pointer
	RET                          

local:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOVB     [R15+#0], R4        ; spill incoming parameter 'v'
	; source: examples/struct_byte_layout.c:71
	MOVB     R0, [R15+#0]        ; R0 = v
	AND      R0, #0x00FF         
	MOV      R1, R15             
	ADD      R1, #2              
	MOVB     [R1], R0            
	; source: examples/struct_byte_layout.c:72
	MOVB     R0, [R15+#0]        ; R0 = v
	AND      R0, #0x00FF         
	MOV      R1, R15             
	ADD      R1, #2              
	MOV      R2, #1              
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     [R3], R0            
	; source: examples/struct_byte_layout.c:73
	MOV      R0, #4660           
	MOV      R1, R15             
	ADD      R1, #2              
	MOV      R2, #2              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      [R3], R0            
	; source: examples/struct_byte_layout.c:74
	MOV      R0, R15             
	ADD      R0, #2              
	MOVB     R1, [R0]            
	AND      R1, #0x00FF         
	MOV      R0, R15             
	ADD      R0, #2              
	MOV      R2, #1              
	MOV      R3, R0              
	ADD      R3, R2              
	MOVB     R0, [R3]            
	AND      R0, #0x00FF         
	MOV      R2, R1              
	ADD      R2, R0              
	MOV      R0, R15             
	ADD      R0, #2              
	MOV      R1, #2              
	MOV      R3, R0              
	ADD      R3, R1              
	MOV      R0, [R3]            
	MOV      R1, R2              
	ADD      R1, R0              
	MOV      R0, R1              ; return value
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

array_de_struct:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'i'
	; source: examples/struct_byte_layout.c:80
	MOV      R0, #ram_tab        ; near address of global
	MOV      R1, [R15+#0]        ; R1 = i
	MOV      R2, #12             
	MULU     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      R0, #5              
	MOV      R2, R1              
	ADD      R2, R0              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #g_cores        ; near address of global
	MOV      R2, [R15+#0]        ; R2 = i
	MOV      R3, #3              
	MULU     R2, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R2, R1              
	ADD      R2, R8              
	MOV      R1, #2              
	MOV      R3, R2              
	ADD      R3, R1              
	MOVB     [R3], R0            
	; source: examples/struct_byte_layout.c:81
	MOV      R0, #g_cores        ; near address of global
	MOV      R1, #6              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, #1              
	MOV      R1, R2              
	ADD      R1, R0              
	MOVB     R0, [R1]            
	AND      R0, #0x00FF         
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

aninhada:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'p'
	MOV      [R15+#2], R5        ; spill incoming parameter 'i'
	; source: examples/struct_byte_layout.c:87
	MOV      R0, [R15+#0]        ; R0 = p
	MOVB     R1, [R0]            
	AND      R1, #0x00FF         
	MOV      R0, [R15+#0]        ; R0 = p
	MOV      R2, #1              
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, #2              
	MOV      R2, R3              
	ADD      R2, R0              
	MOVB     [R2], R1            
	; source: examples/struct_byte_layout.c:88
	MOV      R0, [R15+#0]        ; R0 = p
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, #1              
	MOV      R1, R2              
	ADD      R1, R0              
	MOVB     R0, [R1]            
	AND      R0, #0x00FF         
	MOV      R1, [R15+#0]        ; R1 = p
	MOV      R2, #8              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R15+#2]        ; R1 = i
	MOV      R2, R3              
	ADD      R2, R1              
	MOVB     [R2], R0            
	; source: examples/struct_byte_layout.c:89
	MOV      R0, [R15+#0]        ; R0 = p
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, #2              
	MOV      R1, R2              
	ADD      R1, R0              
	MOV      R0, [R1]            
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

uniao:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'u'
	; source: examples/struct_byte_layout.c:95
	MOV      R0, #4660           
	MOV      R1, [R15+#0]        ; R1 = u
	MOV      [R1], R0            
	; source: examples/struct_byte_layout.c:96
	MOV      R0, [R15+#0]        ; R0 = u
	MOVB     R1, [R0]            
	AND      R1, #0x00FF         
	MOV      R0, [R15+#0]        ; R0 = u
	MOV      R2, #1              
	MOV      R3, R0              
	ADD      R3, R2              
	MOVB     [R3], R1            
	; source: examples/struct_byte_layout.c:97
	MOV      R0, [R15+#0]        ; R0 = u
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

copia:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'dst'
	; source: examples/struct_byte_layout.c:104
	MOV      R0, R15             
	ADD      R0, #2              
	MOV      R1, #g_par          ; near address of global
	MOVB     R2, [R1]            
	AND      R2, #0x00FF         
	MOVB     [R0], R2            
	MOV      R2, #1              
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R2, #1              
	MOV      R8, R1              
	ADD      R8, R2              
	MOVB     R2, [R8]            
	AND      R2, #0x00FF         
	MOVB     [R3], R2            
	MOV      R2, #2              
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, #2              
	MOV      R2, R1              
	ADD      R2, R0              
	MOV      R0, [R2]            
	MOV      [R3], R0            
	; source: examples/struct_byte_layout.c:105
	MOV      R0, R15             
	ADD      R0, #2              
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOV      R1, [R15+#0]        ; R1 = dst
	MOV      R2, #2              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      [R3], R0            
	; source: examples/struct_byte_layout.c:106
	MOV      R0, R15             
	ADD      R0, #2              
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, [R15+#0]        ; R1 = dst
	MOV      R2, #1              
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     [R3], R0            
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

