; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global reinterpret

reinterpret:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #2              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'v'
	; source: /home/alexandre/Projects/centrais_oem/siemens_sir32/compiler/examples/union_basic.c:8
	MOV      R0, [R15+#0]        ; R0 = v
	MOV      R1, [R0]            
	MOV      R0, R1              ; return value
	ADD      SP, #2              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

