; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

	.section .text
	.global bug6
	.global bug7
	.global bug8
	.global bug10
	.global bug11_lt
	.global bug11_eq
	.global bug11_add
	.global bug15

bug6:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #10             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'x'
	MOV      [R15+#2], R5        ; spill incoming parameter 'a'
	MOV      [R15+#4], R6        ; spill incoming parameter 'b'
	; source: examples/wide32_bugs.c:6
	MOV      R0, [R15+#0]        ; R0 = x
	MOV      R1, [R15+#2]        ; R1 = a
	MOV      R2, [R15+#4]        ; R2 = b
	MULU     R1, R2              ; 16x16->32 product in MDH:MDL
	MOV      R3, MDL             ; low word of 32-bit product
	MOV      R1, MDH             ; high word of 32-bit product
	MOV      R2, #0              
	MOV      R8, R0              
	ADD      R8, R3              ; low word of 32-bit operation
	MOV      R0, R2              
	ADDC     R0, R1              ; high word, with carry from the low word
	MOV      [R15+#6], R8        ; r = R8
	MOV      [R15+#8], R0        ; r (high word) = R0
	; source: examples/wide32_bugs.c:7
	MOV      R0, [R15+#6]        ; R0 = r
	ADD      SP, #10             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug7:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #14             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'lo'
	MOV      [R15+#2], R5        ; spill incoming parameter 'hi'
	MOV      [R15+#4], R6        ; spill incoming parameter 'd'
	; source: examples/wide32_bugs.c:12
	MOV      R0, [R15+#2]        ; R0 = hi
	MOV      R1, [R15+#0]        ; R1 = lo
	MOV      [R15+#6], R1        ; low word of composed 32-bit value
	MOV      [R15+#8], R0        ; high word of composed 32-bit value
	; source: examples/wide32_bugs.c:13
	MOV      R0, [R15+#4]        ; R0 = d
	MOV      R11, [R15+#6]       ; low word of 32-bit dividend
	MOV      MDL, R11            
	MOV      R11, [R15+#8]       ; high word of 32-bit dividend
	MOV      MDH, R11            
	DIVLU    R0                  
	MOV      R1, MDL             ; quotient
	MOV      R0, #0              
	MOV      [R15+#10], R1       ; q = R1
	MOV      [R15+#12], R0       ; q (high word) = R0
	; source: examples/wide32_bugs.c:14
	MOV      R0, [R15+#12]       ; high word of 32-bit value
	ADD      SP, #14             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug8:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	; source: examples/wide32_bugs.c:19
	MOV      R0, #53392          
	MOV      R1, #3              
	MOV      [R15+#0], R0        ; x = R0
	MOV      [R15+#2], R1        ; x (high word) = R1
	; source: examples/wide32_bugs.c:20
	MOV      R0, [R15+#2]        ; high word of 32-bit value
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug10:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #14             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'lo'
	MOV      [R15+#2], R5        ; spill incoming parameter 'hi'
	MOV      [R15+#4], R6        ; spill incoming parameter 'neg'
	; source: examples/wide32_bugs.c:25
	MOV      R0, [R15+#2]        ; R0 = hi
	MOV      R1, [R15+#0]        ; R1 = lo
	MOV      [R15+#6], R1        ; low word of composed 32-bit value
	MOV      [R15+#8], R0        ; high word of composed 32-bit value
	; source: examples/wide32_bugs.c:26
	MOV      R0, [R15+#4]        ; R0 = neg
	CMP      R0, #0              
	JMPR     cc_NZ, .Lbug10_tern_true_0
	JMPR     cc_UC, .Lbug10_tern_false_1
.Lbug10_tern_true_0:
	MOV      R0, [R15+#6]        ; R0 = n
	MOV      R1, [R15+#8]        ; R1 = n (high word)
	MOV      R2, #0              
	MOV      R3, #0              
	MOV      R8, R2              
	SUB      R8, R0              ; low word of 32-bit operation
	MOV      R0, R3              
	SUBC     R0, R1              ; high word, with carry from the low word
	MOV      R1, R8              
	MOV      R2, R0              
	JMPR     cc_UC, .Lbug10_tern_end_2
.Lbug10_tern_false_1:
	MOV      R0, [R15+#6]        ; R0 = n
	MOV      R3, [R15+#8]        ; R3 = n (high word)
	MOV      R1, R0              
	MOV      R2, R3              
.Lbug10_tern_end_2:
	MOV      [R15+#10], R1       ; m = R1
	MOV      [R15+#12], R2       ; m (high word) = R2
	; source: examples/wide32_bugs.c:27
	MOV      R0, [R15+#10]       ; R0 = m
	MOV      R1, R0              
	MOV      R0, R1              ; return value
	ADD      SP, #14             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug11_lt:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #16             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'alo'
	MOV      [R15+#2], R5        ; spill incoming parameter 'ahi'
	MOV      [R15+#4], R6        ; spill incoming parameter 'blo'
	MOV      [R15+#6], R7        ; spill incoming parameter 'bhi'
	; source: examples/wide32_bugs.c:32
	MOV      R0, [R15+#2]        ; R0 = ahi
	MOV      R1, [R15+#0]        ; R1 = alo
	MOV      [R15+#8], R1        ; low word of composed 32-bit value
	MOV      [R15+#10], R0       ; high word of composed 32-bit value
	; source: examples/wide32_bugs.c:33
	MOV      R0, [R15+#6]        ; R0 = bhi
	MOV      R1, [R15+#4]        ; R1 = blo
	MOV      [R15+#12], R1       ; low word of composed 32-bit value
	MOV      [R15+#14], R0       ; high word of composed 32-bit value
	; source: examples/wide32_bugs.c:34
	MOV      R0, [R15+#8]        ; R0 = a
	MOV      R1, [R15+#10]       ; R1 = a (high word)
	MOV      R2, [R15+#12]       ; R2 = b
	MOV      R3, [R15+#14]       ; R3 = b (high word)
	CMP      R0, R2              ; 32-bit compare: low words
	MOV      R11, R1             
	SUBC     R11, R3             ; 32-bit compare: high words, with borrow
	JMPR     cc_C, .Lbug11_lt_cmp32_true_1
	MOV      R8, #0              
	JMPR     cc_UC, .Lbug11_lt_cmp32_end_1
.Lbug11_lt_cmp32_true_1:
	MOV      R8, #1              
.Lbug11_lt_cmp32_end_1:
	; source: examples/wide32_bugs.c:37
	CMP      R8, #0              
	JMPR     cc_NZ, .Lbug11_lt_if_then_0
	JMPR     cc_UC, .Lbug11_lt_if_end_2
.Lbug11_lt_if_then_0:
	; source: examples/wide32_bugs.c:35
	MOV      R0, #1              
	ADD      SP, #16             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Lbug11_lt_if_end_2:
	; source: examples/wide32_bugs.c:37
	MOV      R0, #0              
	ADD      SP, #16             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug11_eq:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #16             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'alo'
	MOV      [R15+#2], R5        ; spill incoming parameter 'ahi'
	MOV      [R15+#4], R6        ; spill incoming parameter 'blo'
	MOV      [R15+#6], R7        ; spill incoming parameter 'bhi'
	; source: examples/wide32_bugs.c:42
	MOV      R0, [R15+#2]        ; R0 = ahi
	MOV      R1, [R15+#0]        ; R1 = alo
	MOV      [R15+#8], R1        ; low word of composed 32-bit value
	MOV      [R15+#10], R0       ; high word of composed 32-bit value
	; source: examples/wide32_bugs.c:43
	MOV      R0, [R15+#6]        ; R0 = bhi
	MOV      R1, [R15+#4]        ; R1 = blo
	MOV      [R15+#12], R1       ; low word of composed 32-bit value
	MOV      [R15+#14], R0       ; high word of composed 32-bit value
	; source: examples/wide32_bugs.c:44
	MOV      R0, [R15+#8]        ; R0 = a
	MOV      R1, [R15+#10]       ; R1 = a (high word)
	MOV      R2, [R15+#12]       ; R2 = b
	MOV      R3, [R15+#14]       ; R3 = b (high word)
	CMP      R0, R2              ; 32-bit compare: low words
	JMPR     cc_NZ, .Lbug11_eq_cmp32_true_2
	CMP      R1, R3              ; 32-bit compare: high words
	JMPR     cc_NZ, .Lbug11_eq_cmp32_true_2
	MOV      R8, #1              
	JMPR     cc_UC, .Lbug11_eq_cmp32_end_2
.Lbug11_eq_cmp32_true_2:
	MOV      R8, #0              
.Lbug11_eq_cmp32_end_2:
	; source: examples/wide32_bugs.c:47
	CMP      R8, #0              
	JMPR     cc_NZ, .Lbug11_eq_if_then_0
	JMPR     cc_UC, .Lbug11_eq_if_end_2
.Lbug11_eq_if_then_0:
	; source: examples/wide32_bugs.c:45
	MOV      R0, #1              
	ADD      SP, #16             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Lbug11_eq_if_end_2:
	; source: examples/wide32_bugs.c:47
	MOV      R0, #0              
	ADD      SP, #16             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug11_add:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #14             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'alo'
	MOV      [R15+#2], R5        ; spill incoming parameter 'ahi'
	MOV      [R15+#4], R6        ; spill incoming parameter 'x'
	; source: examples/wide32_bugs.c:52
	MOV      R0, [R15+#2]        ; R0 = ahi
	MOV      R1, [R15+#0]        ; R1 = alo
	MOV      [R15+#6], R1        ; low word of composed 32-bit value
	MOV      [R15+#8], R0        ; high word of composed 32-bit value
	; source: examples/wide32_bugs.c:53
	MOV      R0, [R15+#6]        ; R0 = a
	MOV      R1, [R15+#8]        ; R1 = a (high word)
	MOV      R2, [R15+#4]        ; R2 = x
	MOV      R3, #0              
	MOV      R8, R0              
	ADD      R8, R2              ; low word of 32-bit operation
	MOV      R0, R1              
	ADDC     R0, R3              ; high word, with carry from the low word
	MOV      [R15+#10], R8       ; s = R8
	MOV      [R15+#12], R0       ; s (high word) = R0
	; source: examples/wide32_bugs.c:54
	MOV      R0, [R15+#12]       ; high word of 32-bit value
	ADD      SP, #14             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

bug15:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'lo'
	MOV      [R15+#2], R5        ; spill incoming parameter 'hi'
	MOV      [R15+#4], R6        ; spill incoming parameter 'd'
	; source: examples/wide32_bugs.c:59
	MOV      R0, [R15+#2]        ; R0 = hi
	MOV      R1, [R15+#0]        ; R1 = lo
	MOV      R2, [R15+#4]        ; R2 = d
	MOV      MDL, R1             ; low word of 32-bit dividend
	MOV      MDH, R0             ; high word of 32-bit dividend
	DIVLU    R2                  
	MOV      R3, MDL             ; quotient
	MOV      R0, R3              
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
