; 08_dtc_table.asm - tabela de 60 DTCs, agora DERIVADA por compilação real
; de reimplementacao_c/dtc/dtc_sirius32.{h,c} (via c167cc + port_real_abi.py),
; não mais reimplementada à mão em asm (ver histórico da versão anterior no
; git/notas - a versão hand-written simplificava os 4 arrays paralelos num
; único DTC_AGING; esta versão usa a struct real `dtc_sirius32_state_t`
; inteira, incluindo o array `dtc_sirius32_table` de 60 entradas completo).
;
; Igual antes: este firmware só chama clear()/decay_tick() (nenhum SID
; K-line de leitura/marcação de DTC existe nesta imagem - ver
; kline_dispatcher.c) - mark() está compilado e disponível (chamada real do
; C original), mas nenhum call site do firmware_min aciona ele, mesma
; honestidade documentada na versão anterior.
;
; Trampolins abaixo preservam a MESMA interface que o resto do firmware já
; usa (DTC_INIT/DTC_CLEAR(R0=modo)/DTC_DECAY_TICK, sem valor de retorno) -
; só a implementação por trás mudou, nenhum outro fragmento precisou ser
; editado.

DTC_INIT:
    MOV R4, #g_dtc_state
    CALLA UC, dtc_sirius32_state_init
    RET

DTC_CLEAR:
    MOV R4, #g_dtc_state
    MOV R5, R0
    CALLA UC, dtc_sirius32_clear
    RET

DTC_DECAY_TICK:
    MOV R4, #g_dtc_state
    CALLA UC, dtc_sirius32_decay_tick
    RET

; Generated by c167cc - do not edit by hand.
; Target: Siemens/Infineon C167CR
; See docs/assembly-syntax.md for the syntax and instruction reference.

dtc_sirius32_table:		DW	0,32768,1,0,0,0,1,1,1,16384,1,0,1,85,1,1,2,8192,1,0,2,64,1,2,3,4096,1,0,3,64,1,1,4,2048,1,0,4,24,1,1,5,1024,1,0,5,16,1,0,6,512,1,0,6,4,1,2,7,256,1,0,7,4,1,1,8,128,1,0,8,16,1,1,9,64,1,0,9,16,1,0,10,0,0,0,254,0,0,1,11,0,0,0,254,0,0,2,12,0,0,0,255,0,0,3,13,0,0,0,255,0,0,3,14,0,0,0,254,0,0,0,15,0,0,0,254,0,0,1,16,0,0,1,254,0,0,2,17,0,0,1,254,0,0,1,18,0,0,1,255,0,0,3,19,0,0,1,254,0,0,2,20,0,0,1,254,0,0,1,21,0,0,1,254,0,0,2,22,0,0,1,254,0,0,1,23,0,0,1,254,0,0,3,24,0,0,1,254,0,0,3,25,0,0,1,254,0,0,3,26,0,0,1,254,0,0,3,27,0,0,1,254,0,0,3,28,0,0,1,254,0,0,3,29,0,0,2,254,0,0,3,30,0,0,2,254,0,0,3,31,0,0,2,254,0,0,3,32,0,0,2,254,0,0,3,33,0,0,2,254,0,0,3,34,0,0,2,254,0,0,3,35,0,0,2,254,0,0,3,36,0,0,2,254,0,0,3,37,0,0,2,254,0,0,3,38,0,0,2,254,0,0,2,39,0,0,2,254,0,0,3,40,0,0,2,254,0,0,3,41,0,0,2,254,0,0,0,42,0,0,2,254,0,0,3,43,0,0,2,254,0,0,1,44,0,0,2,254,0,0,3,45,0,0,3,254,0,0,3,46,0,0,3,254,0,0,3,47,0,0,3,254,0,0,3,48,0,0,4,255,0,0,0,49,0,0,4,255,0,0,2,50,0,0,4,255,0,0,1,51,0,0,4,255,0,0,2,52,0,0,4,255,0,0,2,53,0,0,4,255,0,0,3,54,0,0,4,255,0,0,3,55,0,0,4,255,0,0,3,56,0,0,4,255,0,0,3,57,0,0,3,255,0,0,0,58,0,0,3,255,0,0,0,59,0,0,3,255,0,0,0		; array, inicializado
RESERVE g_dtc_state, #72


dtc_sirius32_get:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #4              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOVB     [R15+#0], R4        ; spill incoming parameter 'index'
	; source: /tmp/dtc_fw_module.c:368
	MOVB     R0, [R15+#0]        ; R0 = index
	AND      R0, #0x00FF         
	MOV      R1, #60             
	CMP      R0, R1              
    JMPA NC, .Lcmp_true_1
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_1
.Lcmp_true_1:
	MOV      R2, #1              
.Lcmp_end_1:
	; source: /tmp/dtc_fw_module.c:369
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_get_if_then_0
    JMPA UC, .Ldtc_sirius32_get_if_end_2
.Ldtc_sirius32_get_if_then_0:
	; source: /tmp/dtc_fw_module.c:368
	MOV      R0, #0              
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Ldtc_sirius32_get_if_end_2:
	; source: /tmp/dtc_fw_module.c:369
	MOV      R0, #dtc_sirius32_table; near address of global
	MOVB     R1, [R15+#0]        ; R1 = index
	AND      R1, #0x00FF         
	MOV      R2, #16             
	MUL     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      [R15+#2], R1        ; e = R1
	; source: /tmp/dtc_fw_module.c:370
	MOV      R0, [R15+#2]        ; R0 = e
	ADD      SP, #4              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

dtc_sirius32_state_init:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'st'
	; source: /tmp/dtc_fw_module.c:378
	MOV      R0, #0              
	; source: /tmp/dtc_fw_module.c:381
	MOVB     [R15+#2], R0        ; w = R0
.Ldtc_sirius32_state_init_for_cond_0:
	; source: /tmp/dtc_fw_module.c:378
	MOVB     R0, [R15+#2]        ; R0 = w
	AND      R0, #0x00FF         
	MOV      R1, #5              
	CMP      R0, R1              
    JMPA C, .Lcmp_true_2
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_2
.Lcmp_true_2:
	MOV      R2, #1              
.Lcmp_end_2:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_state_init_for_body_1
    JMPA UC, .Ldtc_sirius32_state_init_for_end_3
.Ldtc_sirius32_state_init_for_body_1:
	; source: /tmp/dtc_fw_module.c:379
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOVB     R2, [R15+#2]        ; R2 = w
	AND      R2, #0x00FF         
	MOV      R3, #2              
	MUL     R2, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R2, R1              
	ADD      R2, R8              
	MOV      [R2], R0            
	; source: /tmp/dtc_fw_module.c:380
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #10             
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     R1, [R15+#2]        ; R1 = w
	AND      R1, #0x00FF         
	MOV      R2, #2              
	MUL     R1, R2              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R1, R3              
	ADD      R1, R8              
	MOV      [R1], R0            
.Ldtc_sirius32_state_init_for_post_2:
	; source: /tmp/dtc_fw_module.c:378
	MOVB     R0, [R15+#2]        ; R0 = w
	AND      R0, #0x00FF         
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     [R15+#2], R2        ; w = R2
    JMPA UC, .Ldtc_sirius32_state_init_for_cond_0
.Ldtc_sirius32_state_init_for_end_3:
	; source: /tmp/dtc_fw_module.c:382
	MOV      R0, #0              
	; source: /tmp/dtc_fw_module.c:384
	MOVB     [R15+#4], R0        ; a = R0
.Ldtc_sirius32_state_init_for_cond_4:
	; source: /tmp/dtc_fw_module.c:382
	MOVB     R0, [R15+#4]        ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #46             
	CMP      R0, R1              
    JMPA C, .Lcmp_true_3
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_3
.Lcmp_true_3:
	MOV      R2, #1              
.Lcmp_end_3:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_state_init_for_body_5
    JMPA UC, .Ldtc_sirius32_state_init_for_end_7
.Ldtc_sirius32_state_init_for_body_5:
	; source: /tmp/dtc_fw_module.c:383
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #20             
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     R1, [R15+#4]        ; R1 = a
	AND      R1, #0x00FF         
	MOV      R2, R3              
	ADD      R2, R1              
	MOVB     [R2], R0            
.Ldtc_sirius32_state_init_for_post_6:
	; source: /tmp/dtc_fw_module.c:382
	MOVB     R0, [R15+#4]        ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     [R15+#4], R2        ; a = R2
    JMPA UC, .Ldtc_sirius32_state_init_for_cond_4
.Ldtc_sirius32_state_init_for_end_7:
	; source: /tmp/dtc_fw_module.c:385
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #68             
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      [R3], R0            
	; source: /tmp/dtc_fw_module.c:386
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #70             
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      [R3], R0            
	; source: /tmp/dtc_fw_module.c:393
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #66             
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      [R3], R0            
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

dtc_sirius32_mark:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #12             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'st'
	MOVB     [R15+#2], R5        ; spill incoming parameter 'index'
	MOV      [R15+#4], R6        ; spill incoming parameter 'set'
	; source: /tmp/dtc_fw_module.c:398
	MOVB     R0, [R15+#2]        ; R0 = index
	AND      R0, #0x00FF         
	MOV      R4, R0              
    CALLA UC, dtc_sirius32_get
	MOV      R1, R0              ; function result
	MOV      [R15+#6], R1        ; e = R1
	; source: /tmp/dtc_fw_module.c:399
	MOV      R0, [R15+#6]        ; R0 = e
	CMP      R0, #0              
    JMPA Z, .Lnot_true_1
	MOV      R1, #0              
    JMPA UC, .Lnot_end_1
.Lnot_true_1:
	MOV      R1, #1              
.Lnot_end_1:
	; source: /tmp/dtc_fw_module.c:401
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_0
    JMPA UC, .Ldtc_sirius32_mark_if_end_2
.Ldtc_sirius32_mark_if_then_0:
	; source: /tmp/dtc_fw_module.c:399
	MOV      R0, #0              
	ADD      SP, #12             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Ldtc_sirius32_mark_if_end_2:
	; source: /tmp/dtc_fw_module.c:401
	MOV      R0, [R15+#4]        ; R0 = set
	CMP      R0, #0              
    JMPA Z, .Lnot_true_2
	MOV      R1, #0              
    JMPA UC, .Lnot_end_2
.Lnot_true_2:
	MOV      R1, #1              
.Lnot_end_2:
	; source: /tmp/dtc_fw_module.c:409
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_3
    JMPA UC, .Ldtc_sirius32_mark_if_end_5
.Ldtc_sirius32_mark_if_then_3:
	; source: /tmp/dtc_fw_module.c:403
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	CMP      R0, #0              
    JMPA Z, .Lnot_true_3
	MOV      R1, #0              
    JMPA UC, .Lnot_end_3
.Lnot_true_3:
	MOV      R1, #1              
.Lnot_end_3:
	; source: /tmp/dtc_fw_module.c:404
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_6
    JMPA UC, .Ldtc_sirius32_mark_if_end_8
.Ldtc_sirius32_mark_if_then_6:
	; source: /tmp/dtc_fw_module.c:403
	MOV      R0, #0              
	ADD      SP, #12             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Ldtc_sirius32_mark_if_end_8:
	; source: /tmp/dtc_fw_module.c:404
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOV      R1, R0              
	CPL      R1                  
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R2, [R15+#6]        ; R2 = e
	MOV      R3, #6              
	MOV      R8, R2              
	ADD      R8, R3              
	MOVB     R2, [R8]            
	AND      R2, #0x00FF         
	MOV      R3, #2              
	MUL     R2, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R2, R0              
	ADD      R2, R8              
	MOV      R0, [R2]            
	MOV      R2, R0              
	AND      R2, R1              
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, [R15+#6]        ; R1 = e
	MOV      R3, #6              
	MOV      R8, R1              
	ADD      R8, R3              
	MOVB     R1, [R8]            
	AND      R1, #0x00FF         
	MOV      R3, #2              
	MUL     R1, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R8              
	MOV      [R1], R2            
	; source: /tmp/dtc_fw_module.c:405
	MOV      R0, #1              
	ADD      SP, #12             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Ldtc_sirius32_mark_if_end_5:
	; source: /tmp/dtc_fw_module.c:409
	MOV      R0, #0              
	MOV      [R15+#8], R0        ; touched_status = R0
	; source: /tmp/dtc_fw_module.c:410
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	; source: /tmp/dtc_fw_module.c:415
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_9
    JMPA UC, .Ldtc_sirius32_mark_if_end_11
.Ldtc_sirius32_mark_if_then_9:
	; source: /tmp/dtc_fw_module.c:411
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, [R15+#6]        ; R2 = e
	MOV      R3, #6              
	MOV      R8, R2              
	ADD      R8, R3              
	MOVB     R2, [R8]            
	AND      R2, #0x00FF         
	MOV      R3, #2              
	MUL     R2, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R2, R1              
	ADD      R2, R8              
	MOV      R1, [R2]            
	MOV      R2, R1              
	OR       R2, R0              
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, [R15+#6]        ; R1 = e
	MOV      R3, #6              
	MOV      R8, R1              
	ADD      R8, R3              
	MOVB     R1, [R8]            
	AND      R1, #0x00FF         
	MOV      R3, #2              
	MUL     R1, R3              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R8              
	MOV      [R1], R2            
	; source: /tmp/dtc_fw_module.c:412
	MOV      R0, #1              
	MOV      [R15+#8], R0        ; touched_status = R0
.Ldtc_sirius32_mark_if_end_11:
	; source: /tmp/dtc_fw_module.c:415
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, #66             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	; source: /tmp/dtc_fw_module.c:435
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_12
    JMPA UC, .Ldtc_sirius32_mark_if_end_14
.Ldtc_sirius32_mark_if_then_12:
	; source: /tmp/dtc_fw_module.c:418
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #8              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #255            
	CMP      R0, R1              
    JMPA NZ, .Lcmp_true_4
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_4
.Lcmp_true_4:
	MOV      R2, #1              
.Lcmp_end_4:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_mark_and_rhs_22
    JMPA UC, .Ldtc_sirius32_mark_logic_false_24
.Ldtc_sirius32_mark_and_rhs_22:
	; source: /tmp/dtc_fw_module.c:419
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #8              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #46             
	CMP      R0, R1              
    JMPA C, .Lcmp_true_5
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_5
.Lcmp_true_5:
	MOV      R2, #1              
.Lcmp_end_5:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_mark_logic_true_23
    JMPA UC, .Ldtc_sirius32_mark_logic_false_24
.Ldtc_sirius32_mark_logic_true_23:
	MOV      R0, #1              
    JMPA UC, .Ldtc_sirius32_mark_logic_end_25
.Ldtc_sirius32_mark_logic_false_24:
	MOV      R0, #0              
.Ldtc_sirius32_mark_logic_end_25:
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_mark_and_rhs_18
    JMPA UC, .Ldtc_sirius32_mark_logic_false_20
.Ldtc_sirius32_mark_and_rhs_18:
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #12             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_mark_logic_true_19
    JMPA UC, .Ldtc_sirius32_mark_logic_false_20
.Ldtc_sirius32_mark_logic_true_19:
	MOV      R0, #1              
    JMPA UC, .Ldtc_sirius32_mark_logic_end_21
.Ldtc_sirius32_mark_logic_false_20:
	MOV      R0, #0              
.Ldtc_sirius32_mark_logic_end_21:
	; source: /tmp/dtc_fw_module.c:428
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_15
    JMPA UC, .Ldtc_sirius32_mark_if_else_16
.Ldtc_sirius32_mark_if_then_15:
	; source: /tmp/dtc_fw_module.c:420
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, #20             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #8              
	MOV      R3, R0              
	ADD      R3, R1              
	MOVB     R0, [R3]            
	AND      R0, #0x00FF         
	MOV      R1, R2              
	ADD      R1, R0              
	MOVB     R0, [R1]            
	AND      R0, #0x00FF         
	MOV      R1, [R15+#6]        ; R1 = e
	MOV      R2, #10             
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     R1, [R3]            
	AND      R1, #0x00FF         
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      [R15+#10], R2       ; sum = R2
	; source: /tmp/dtc_fw_module.c:421
	MOV      R0, [R15+#10]       ; R0 = sum
	MOV      R1, #255            
	CMP      R0, R1              
    JMPA UGT, .Lcmp_true_6
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_6
.Lcmp_true_6:
	MOV      R2, #1              
.Lcmp_end_6:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_mark_tern_true_26
    JMPA UC, .Ldtc_sirius32_mark_tern_false_27
.Ldtc_sirius32_mark_tern_true_26:
	MOV      R0, #255            
	MOV      R1, R0              
    JMPA UC, .Ldtc_sirius32_mark_tern_end_28
.Ldtc_sirius32_mark_tern_false_27:
	MOV      R0, [R15+#10]       ; R0 = sum
	MOV      R1, R0              
.Ldtc_sirius32_mark_tern_end_28:
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R2, #20             
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R2, #8              
	MOV      R8, R0              
	ADD      R8, R2              
	MOVB     R0, [R8]            
	AND      R0, #0x00FF         
	MOV      R2, R3              
	ADD      R2, R0              
	MOVB     [R2], R1            
    JMPA UC, .Ldtc_sirius32_mark_if_end_17
.Ldtc_sirius32_mark_if_else_16:
	; source: /tmp/dtc_fw_module.c:422
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #8              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #255            
	CMP      R0, R1              
    JMPA Z, .Lcmp_true_7
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_7
.Lcmp_true_7:
	MOV      R2, #1              
.Lcmp_end_7:
	; source: /tmp/dtc_fw_module.c:428
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_29
    JMPA UC, .Ldtc_sirius32_mark_if_end_31
.Ldtc_sirius32_mark_if_then_29:
.Ldtc_sirius32_mark_if_end_31:
.Ldtc_sirius32_mark_if_end_17:
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	; source: /tmp/dtc_fw_module.c:433
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_32
    JMPA UC, .Ldtc_sirius32_mark_if_end_34
.Ldtc_sirius32_mark_if_then_32:
	; source: /tmp/dtc_fw_module.c:429
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #10             
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R15+#6]        ; R1 = e
	MOV      R2, #6              
	MOV      R8, R1              
	ADD      R8, R2              
	MOVB     R1, [R8]            
	AND      R1, #0x00FF         
	MOV      R2, #2              
	MUL     R1, R2              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R1, R3              
	ADD      R1, R8              
	MOV      R2, [R1]            
	MOV      R1, R2              
	OR       R1, R0              
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R2, #10             
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R2, #6              
	MOV      R8, R0              
	ADD      R8, R2              
	MOVB     R0, [R8]            
	AND      R0, #0x00FF         
	MOV      R2, #2              
	MUL     R0, R2              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R0, R3              
	ADD      R0, R8              
	MOV      [R0], R1            
	; source: /tmp/dtc_fw_module.c:430
	MOV      R0, #1              
	MOV      [R15+#8], R0        ; touched_status = R0
	; source: /tmp/dtc_fw_module.c:431
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, #68             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	; source: /tmp/dtc_fw_module.c:432
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_mark_if_then_35
    JMPA UC, .Ldtc_sirius32_mark_if_end_37
.Ldtc_sirius32_mark_if_then_35:
	; source: /tmp/dtc_fw_module.c:431
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, #68             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOVB     R1, [R15+#2]        ; R1 = index
	AND      R1, #0x00FF         
	MOV      R2, [R15+#0]        ; R2 = st
	MOV      R3, #70             
	MOV      R8, R2              
	ADD      R8, R3              
	MOV      R2, [R8]            
	MOV      R4, R1              
	MOV      R5, R2              
	CALLI    cc_UC, R0           
	MOV      R3, R0              ; function result
.Ldtc_sirius32_mark_if_end_37:
.Ldtc_sirius32_mark_if_end_34:
.Ldtc_sirius32_mark_if_end_14:
	; source: /tmp/dtc_fw_module.c:435
	MOV      R0, [R15+#8]        ; R0 = touched_status
	ADD      SP, #12             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

dtc_sirius32_decay_tick:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #8              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'st'
	; source: /tmp/dtc_fw_module.c:454
	MOV      R0, #0              
	; source: /tmp/dtc_fw_module.c:467
	MOVB     [R15+#2], R0        ; i = R0
.Ldtc_sirius32_decay_tick_for_cond_0:
	; source: /tmp/dtc_fw_module.c:454
	MOVB     R0, [R15+#2]        ; R0 = i
	AND      R0, #0x00FF         
	MOV      R1, #60             
	CMP      R0, R1              
    JMPA C, .Lcmp_true_8
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_8
.Lcmp_true_8:
	MOV      R2, #1              
.Lcmp_end_8:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_for_body_1
    JMPA UC, .Ldtc_sirius32_decay_tick_for_end_3
.Ldtc_sirius32_decay_tick_for_body_1:
	; source: /tmp/dtc_fw_module.c:455
	MOV      R0, #dtc_sirius32_table; near address of global
	MOVB     R1, [R15+#2]        ; R1 = i
	AND      R1, #0x00FF         
	MOV      R2, #16             
	MUL     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      [R15+#4], R1        ; e = R1
	; source: /tmp/dtc_fw_module.c:456
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #8              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #255            
	CMP      R0, R1              
    JMPA Z, .Lcmp_true_9
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_9
.Lcmp_true_9:
	MOV      R2, #1              
.Lcmp_end_9:
	; source: /tmp/dtc_fw_module.c:457
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_if_then_4
    JMPA UC, .Ldtc_sirius32_decay_tick_if_end_6
.Ldtc_sirius32_decay_tick_if_then_4:
    JMPA UC, .Ldtc_sirius32_decay_tick_for_post_2
.Ldtc_sirius32_decay_tick_if_end_6:
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #8              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #46             
	CMP      R0, R1              
    JMPA NC, .Lcmp_true_10
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_10
.Lcmp_true_10:
	MOV      R2, #1              
.Lcmp_end_10:
	; source: /tmp/dtc_fw_module.c:458
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_if_then_7
    JMPA UC, .Ldtc_sirius32_decay_tick_if_end_9
.Ldtc_sirius32_decay_tick_if_then_7:
    JMPA UC, .Ldtc_sirius32_decay_tick_for_post_2
.Ldtc_sirius32_decay_tick_if_end_9:
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #12             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	CMP      R0, #0              
    JMPA Z, .Lnot_true_4
	MOV      R1, #0              
    JMPA UC, .Lnot_end_4
.Lnot_true_4:
	MOV      R1, #1              
.Lnot_end_4:
	; source: /tmp/dtc_fw_module.c:460
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_if_then_10
    JMPA UC, .Ldtc_sirius32_decay_tick_if_end_12
.Ldtc_sirius32_decay_tick_if_then_10:
    JMPA UC, .Ldtc_sirius32_decay_tick_for_post_2
.Ldtc_sirius32_decay_tick_if_end_12:
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, #20             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #8              
	MOV      R3, R0              
	ADD      R3, R1              
	MOVB     R0, [R3]            
	AND      R0, #0x00FF         
	MOV      R1, R2              
	ADD      R1, R0              
	MOVB     R0, [R1]            
	AND      R0, #0x00FF         
	MOV      R1, [R15+#4]        ; R1 = e
	MOV      R2, #10             
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     R1, [R3]            
	AND      R1, #0x00FF         
	MOV      R2, R0              
	SUB      R2, R1              
	MOV      [R15+#6], R2        ; v = R2
	; source: /tmp/dtc_fw_module.c:461
	MOV      R0, [R15+#6]        ; R0 = v
	MOV      R1, #0              
	CMP      R0, R1              
    JMPA SLT, .Lcmp_true_11
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_11
.Lcmp_true_11:
	MOV      R2, #1              
.Lcmp_end_11:
	; source: /tmp/dtc_fw_module.c:462
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_if_then_13
    JMPA UC, .Ldtc_sirius32_decay_tick_if_end_15
.Ldtc_sirius32_decay_tick_if_then_13:
	; source: /tmp/dtc_fw_module.c:461
	MOV      R0, #0              
	MOV      [R15+#6], R0        ; v = R0
.Ldtc_sirius32_decay_tick_if_end_15:
	; source: /tmp/dtc_fw_module.c:462
	MOV      R0, [R15+#6]        ; R0 = v
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #20             
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R15+#4]        ; R1 = e
	MOV      R2, #8              
	MOV      R8, R1              
	ADD      R8, R2              
	MOVB     R1, [R8]            
	AND      R1, #0x00FF         
	MOV      R2, R3              
	ADD      R2, R1              
	MOVB     [R2], R0            
	; source: /tmp/dtc_fw_module.c:464
	MOV      R0, [R15+#6]        ; R0 = v
	MOV      R1, #128            
	CMP      R0, R1              
    JMPA SLT, .Lcmp_true_12
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_12
.Lcmp_true_12:
	MOV      R2, #1              
.Lcmp_end_12:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_and_rhs_19
    JMPA UC, .Ldtc_sirius32_decay_tick_logic_false_21
.Ldtc_sirius32_decay_tick_and_rhs_19:
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_logic_true_20
    JMPA UC, .Ldtc_sirius32_decay_tick_logic_false_21
.Ldtc_sirius32_decay_tick_logic_true_20:
	MOV      R0, #1              
    JMPA UC, .Ldtc_sirius32_decay_tick_logic_end_22
.Ldtc_sirius32_decay_tick_logic_false_21:
	MOV      R0, #0              
.Ldtc_sirius32_decay_tick_logic_end_22:
	; source: /tmp/dtc_fw_module.c:467
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_decay_tick_if_then_16
    JMPA UC, .Ldtc_sirius32_decay_tick_if_end_18
.Ldtc_sirius32_decay_tick_if_then_16:
	; source: /tmp/dtc_fw_module.c:465
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #2              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	MOV      R1, R0              
	CPL      R1                  
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R2, #10             
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R2, #6              
	MOV      R8, R0              
	ADD      R8, R2              
	MOVB     R0, [R8]            
	AND      R0, #0x00FF         
	MOV      R2, #2              
	MUL     R0, R2              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R0, R3              
	ADD      R0, R8              
	MOV      R2, [R0]            
	MOV      R0, R2              
	AND      R0, R1              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #10             
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R15+#4]        ; R1 = e
	MOV      R2, #6              
	MOV      R8, R1              
	ADD      R8, R2              
	MOVB     R1, [R8]            
	AND      R1, #0x00FF         
	MOV      R2, #2              
	MUL     R1, R2              
	MOV      R8, MDL             ; low word of MDL:MDH product
	MOV      R1, R3              
	ADD      R1, R8              
	MOV      [R1], R0            
.Ldtc_sirius32_decay_tick_if_end_18:
.Ldtc_sirius32_decay_tick_for_post_2:
	; source: /tmp/dtc_fw_module.c:454
	MOVB     R0, [R15+#2]        ; R0 = i
	AND      R0, #0x00FF         
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     [R15+#2], R2        ; i = R2
    JMPA UC, .Ldtc_sirius32_decay_tick_for_cond_0
.Ldtc_sirius32_decay_tick_for_end_3:
	ADD      SP, #8              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

dtc_sirius32_clear:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #12             ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'st'
	MOV      [R15+#2], R5        ; spill incoming parameter 'mode'
	; source: /tmp/dtc_fw_module.c:473
	MOV      R0, [R15+#2]        ; R0 = mode
	MOV      R1, #2              
	CMP      R0, R1              
    JMPA Z, .Lcmp_true_13
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_13
.Lcmp_true_13:
	MOV      R2, #1              
.Lcmp_end_13:
	; source: /tmp/dtc_fw_module.c:493
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_clear_if_then_0
    JMPA UC, .Ldtc_sirius32_clear_if_end_2
.Ldtc_sirius32_clear_if_then_0:
	; source: /tmp/dtc_fw_module.c:474
	MOV      R0, #0              
	; source: /tmp/dtc_fw_module.c:483
	MOVB     [R15+#4], R0        ; i = R0
.Ldtc_sirius32_clear_for_cond_3:
	; source: /tmp/dtc_fw_module.c:474
	MOVB     R0, [R15+#4]        ; R0 = i
	AND      R0, #0x00FF         
	MOV      R1, #60             
	CMP      R0, R1              
    JMPA C, .Lcmp_true_14
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_14
.Lcmp_true_14:
	MOV      R2, #1              
.Lcmp_end_14:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_clear_for_body_4
    JMPA UC, .Ldtc_sirius32_clear_for_end_6
.Ldtc_sirius32_clear_for_body_4:
	; source: /tmp/dtc_fw_module.c:475
	MOV      R0, #dtc_sirius32_table; near address of global
	MOVB     R1, [R15+#4]        ; R1 = i
	AND      R1, #0x00FF         
	MOV      R2, #16             
	MUL     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      [R15+#6], R1        ; e = R1
	; source: /tmp/dtc_fw_module.c:476
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	CMP      R0, #0              
    JMPA Z, .Lnot_true_5
	MOV      R1, #0              
    JMPA UC, .Lnot_end_5
.Lnot_true_5:
	MOV      R1, #1              
.Lnot_end_5:
	; source: /tmp/dtc_fw_module.c:477
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_clear_if_then_7
    JMPA UC, .Ldtc_sirius32_clear_if_end_9
.Ldtc_sirius32_clear_if_then_7:
    JMPA UC, .Ldtc_sirius32_clear_for_post_5
.Ldtc_sirius32_clear_if_end_9:
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #8              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #255            
	CMP      R0, R1              
    JMPA Z, .Lcmp_true_15
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_15
.Lcmp_true_15:
	MOV      R2, #1              
.Lcmp_end_15:
	; source: /tmp/dtc_fw_module.c:478
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_clear_if_then_10
    JMPA UC, .Ldtc_sirius32_clear_if_end_12
.Ldtc_sirius32_clear_if_then_10:
    JMPA UC, .Ldtc_sirius32_clear_for_post_5
.Ldtc_sirius32_clear_if_end_12:
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #8              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     R0, [R2]            
	AND      R0, #0x00FF         
	MOV      R1, #46             
	CMP      R0, R1              
    JMPA NC, .Lcmp_true_16
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_16
.Lcmp_true_16:
	MOV      R2, #1              
.Lcmp_end_16:
	; source: /tmp/dtc_fw_module.c:479
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_clear_if_then_13
    JMPA UC, .Ldtc_sirius32_clear_if_end_15
.Ldtc_sirius32_clear_if_then_13:
    JMPA UC, .Ldtc_sirius32_clear_for_post_5
.Ldtc_sirius32_clear_if_end_15:
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, #10             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R1, #6              
	MOV      R3, R0              
	ADD      R3, R1              
	MOVB     R0, [R3]            
	AND      R0, #0x00FF         
	MOV      R1, #2              
	MUL     R0, R1              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R0, R2              
	ADD      R0, R3              
	MOV      R1, [R0]            
	MOV      R0, [R15+#6]        ; R0 = e
	MOV      R2, #2              
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, [R3]            
	MOV      R2, R1              
	AND      R2, R0              
	MOV      R0, #0              
	CMP      R2, R0              
    JMPA NZ, .Lcmp_true_17
	MOV      R1, #0              
    JMPA UC, .Lcmp_end_17
.Lcmp_true_17:
	MOV      R1, #1              
.Lcmp_end_17:
	MOV      [R15+#8], R1        ; is_confirmed = R1
	; source: /tmp/dtc_fw_module.c:480
	MOV      R0, [R15+#8]        ; R0 = is_confirmed
	; source: /tmp/dtc_fw_module.c:483
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_clear_if_then_16
    JMPA UC, .Ldtc_sirius32_clear_if_end_18
.Ldtc_sirius32_clear_if_then_16:
	; source: /tmp/dtc_fw_module.c:481
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #20             
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R15+#6]        ; R1 = e
	MOV      R2, #8              
	MOV      R8, R1              
	ADD      R8, R2              
	MOVB     R1, [R8]            
	AND      R1, #0x00FF         
	MOV      R2, R3              
	ADD      R2, R1              
	MOVB     [R2], R0            
.Ldtc_sirius32_clear_if_end_18:
.Ldtc_sirius32_clear_for_post_5:
	; source: /tmp/dtc_fw_module.c:474
	MOVB     R0, [R15+#4]        ; R0 = i
	AND      R0, #0x00FF         
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     [R15+#4], R2        ; i = R2
    JMPA UC, .Ldtc_sirius32_clear_for_cond_3
.Ldtc_sirius32_clear_for_end_6:
	; source: /tmp/dtc_fw_module.c:484
	ADD      SP, #12             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Ldtc_sirius32_clear_if_end_2:
	; source: /tmp/dtc_fw_module.c:493
	MOV      R0, #0              
	; source: /tmp/dtc_fw_module.c:495
	MOVB     [R15+#10], R0       ; a = R0
.Ldtc_sirius32_clear_for_cond_19:
	; source: /tmp/dtc_fw_module.c:493
	MOVB     R0, [R15+#10]       ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #46             
	CMP      R0, R1              
    JMPA C, .Lcmp_true_18
	MOV      R2, #0              
    JMPA UC, .Lcmp_end_18
.Lcmp_true_18:
	MOV      R2, #1              
.Lcmp_end_18:
	CMP      R2, #0              
    JMPA NZ, .Ldtc_sirius32_clear_for_body_20
    JMPA UC, .Ldtc_sirius32_clear_for_end_22
.Ldtc_sirius32_clear_for_body_20:
	; source: /tmp/dtc_fw_module.c:494
	MOV      R0, #0              
	MOV      R1, [R15+#0]        ; R1 = st
	MOV      R2, #20             
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     R1, [R15+#10]       ; R1 = a
	AND      R1, #0x00FF         
	MOV      R2, R3              
	ADD      R2, R1              
	MOVB     [R2], R0            
.Ldtc_sirius32_clear_for_post_21:
	; source: /tmp/dtc_fw_module.c:493
	MOVB     R0, [R15+#10]       ; R0 = a
	AND      R0, #0x00FF         
	MOV      R1, #1              
	MOV      R2, R0              
	ADD      R2, R1              
	MOVB     [R15+#10], R2       ; a = R2
    JMPA UC, .Ldtc_sirius32_clear_for_cond_19
.Ldtc_sirius32_clear_for_end_22:
	ADD      SP, #12             ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

dtc_sirius32_is_pending:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'st'
	MOVB     [R15+#2], R5        ; spill incoming parameter 'index'
	; source: /tmp/dtc_fw_module.c:500
	MOVB     R0, [R15+#2]        ; R0 = index
	AND      R0, #0x00FF         
	MOV      R4, R0              
    CALLA UC, dtc_sirius32_get
	MOV      R1, R0              ; function result
	MOV      [R15+#4], R1        ; e = R1
	; source: /tmp/dtc_fw_module.c:501
	MOV      R0, [R15+#4]        ; R0 = e
	CMP      R0, #0              
    JMPA Z, .Lnot_true_6
	MOV      R1, #0              
    JMPA UC, .Lnot_end_6
.Lnot_true_6:
	MOV      R1, #1              
.Lnot_end_6:
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_is_pending_logic_true_4
.Ldtc_sirius32_is_pending_or_rhs_3:
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	CMP      R0, #0              
    JMPA Z, .Lnot_true_7
	MOV      R1, #0              
    JMPA UC, .Lnot_end_7
.Lnot_true_7:
	MOV      R1, #1              
.Lnot_end_7:
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_is_pending_logic_true_4
    JMPA UC, .Ldtc_sirius32_is_pending_logic_false_5
.Ldtc_sirius32_is_pending_logic_true_4:
	MOV      R0, #1              
    JMPA UC, .Ldtc_sirius32_is_pending_logic_end_6
.Ldtc_sirius32_is_pending_logic_false_5:
	MOV      R0, #0              
.Ldtc_sirius32_is_pending_logic_end_6:
	; source: /tmp/dtc_fw_module.c:502
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_is_pending_if_then_0
    JMPA UC, .Ldtc_sirius32_is_pending_if_end_2
.Ldtc_sirius32_is_pending_if_then_0:
	; source: /tmp/dtc_fw_module.c:501
	MOV      R0, #0              
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Ldtc_sirius32_is_pending_if_end_2:
	; source: /tmp/dtc_fw_module.c:502
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, [R15+#4]        ; R1 = e
	MOV      R2, #6              
	MOV      R3, R1              
	ADD      R3, R2              
	MOVB     R1, [R3]            
	AND      R1, #0x00FF         
	MOV      R2, #2              
	MUL     R1, R2              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R1, R0              
	ADD      R1, R3              
	MOV      R0, [R1]            
	MOV      R1, [R15+#4]        ; R1 = e
	MOV      R2, #2              
	MOV      R3, R1              
	ADD      R3, R2              
	MOV      R1, [R3]            
	MOV      R2, R0              
	AND      R2, R1              
	MOV      R0, #0              
	CMP      R2, R0              
    JMPA NZ, .Lcmp_true_19
	MOV      R1, #0              
    JMPA UC, .Lcmp_end_19
.Lcmp_true_19:
	MOV      R1, #1              
.Lcmp_end_19:
	MOV      R0, R1              ; return value
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

dtc_sirius32_is_confirmed:
	PUSH     R15                 ; save caller's frame pointer
	SUB      SP, #6              ; allocate locals + spills
	MOV      R15, SP             ; establish frame pointer
	MOV      [R15+#0], R4        ; spill incoming parameter 'st'
	MOVB     [R15+#2], R5        ; spill incoming parameter 'index'
	; source: /tmp/dtc_fw_module.c:507
	MOVB     R0, [R15+#2]        ; R0 = index
	AND      R0, #0x00FF         
	MOV      R4, R0              
    CALLA UC, dtc_sirius32_get
	MOV      R1, R0              ; function result
	MOV      [R15+#4], R1        ; e = R1
	; source: /tmp/dtc_fw_module.c:508
	MOV      R0, [R15+#4]        ; R0 = e
	CMP      R0, #0              
    JMPA Z, .Lnot_true_8
	MOV      R1, #0              
    JMPA UC, .Lnot_end_8
.Lnot_true_8:
	MOV      R1, #1              
.Lnot_end_8:
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_is_confirmed_logic_true_4
.Ldtc_sirius32_is_confirmed_or_rhs_3:
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #4              
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R2]            
	CMP      R0, #0              
    JMPA Z, .Lnot_true_9
	MOV      R1, #0              
    JMPA UC, .Lnot_end_9
.Lnot_true_9:
	MOV      R1, #1              
.Lnot_end_9:
	CMP      R1, #0              
    JMPA NZ, .Ldtc_sirius32_is_confirmed_logic_true_4
    JMPA UC, .Ldtc_sirius32_is_confirmed_logic_false_5
.Ldtc_sirius32_is_confirmed_logic_true_4:
	MOV      R0, #1              
    JMPA UC, .Ldtc_sirius32_is_confirmed_logic_end_6
.Ldtc_sirius32_is_confirmed_logic_false_5:
	MOV      R0, #0              
.Ldtc_sirius32_is_confirmed_logic_end_6:
	; source: /tmp/dtc_fw_module.c:509
	CMP      R0, #0              
    JMPA NZ, .Ldtc_sirius32_is_confirmed_if_then_0
    JMPA UC, .Ldtc_sirius32_is_confirmed_if_end_2
.Ldtc_sirius32_is_confirmed_if_then_0:
	; source: /tmp/dtc_fw_module.c:508
	MOV      R0, #0              
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          
.Ldtc_sirius32_is_confirmed_if_end_2:
	; source: /tmp/dtc_fw_module.c:509
	MOV      R0, [R15+#0]        ; R0 = st
	MOV      R1, #10             
	MOV      R2, R0              
	ADD      R2, R1              
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R1, #6              
	MOV      R3, R0              
	ADD      R3, R1              
	MOVB     R0, [R3]            
	AND      R0, #0x00FF         
	MOV      R1, #2              
	MUL     R0, R1              
	MOV      R3, MDL             ; low word of MDL:MDH product
	MOV      R0, R2              
	ADD      R0, R3              
	MOV      R1, [R0]            
	MOV      R0, [R15+#4]        ; R0 = e
	MOV      R2, #2              
	MOV      R3, R0              
	ADD      R3, R2              
	MOV      R0, [R3]            
	MOV      R2, R1              
	AND      R2, R0              
	MOV      R0, #0              
	CMP      R2, R0              
    JMPA NZ, .Lcmp_true_20
	MOV      R1, #0              
    JMPA UC, .Lcmp_end_20
.Lcmp_true_20:
	MOV      R1, #1              
.Lcmp_end_20:
	MOV      R0, R1              ; return value
	ADD      SP, #6              ; release locals + spills
	POP      R15                 ; restore caller's frame pointer
	RET                          

